- build/package/orb-agent/Dockerfile
- build/package/orb-agent/files/vector.toml
- build/package/orb-agent/scripts/entrypoint
- build/package/orb-agent/scripts/run-pktvisord.sh
- docker-compose.yml
infux is for demo purposes only, need to get vectors remote_write prometheus sink configured
> adds a dev compose file to get metrics shipping

- .github/workflows/go.yml
- Makefile
- agent/agent.go
- agent/cloud_config/cloud_config.go
- agent/config/types.go
- agent/docker/Dockerfile
- agent/docker/agent.yaml
- cmd/agent/config.example.yaml
- cmd/agent/main.go
- Dockerfile for orb-agent
- configuration updates for env variable config
- CI for orb-agent
> create orb-agent container

- ui/src/environments/environment.defaults.ts
- ui/src/environments/environment.prod.ts
Minor improvements on UI Angular environment configuration.
> feat(ui-env-config): minor improvements on environment config.

- ui/src/environments/environment.defaults.ts
* fix loginUrl '/tokens/api/v1' -> '/tokens'
Revert versioning of tokens endpoint
> fix(orb-ui env.prod-angular): wrong login endpoint. not versioned yet.

- sinks/api/endpoint.go
- sinks/api/endpoint_test.go
- sinks/api/logging.go
- sinks/api/metrics.go
- sinks/api/openapi.yaml
- sinks/api/requests.go
- sinks/api/responses.go
- sinks/api/transport.go
- sinks/redis/producer/streams.go
- sinks/sinks.go
- sinks/sinks_service.go
- sinks/sinks_service_test.go
> Resolves #83 Sink validation endpoint

- fleet/api/openapi.yaml
Openapi spec to Agent on fleet management
> feat(agent): openapi specification for agent

- sinks/api/endpoint_test.go
- sinks/api/transport.go
- sinks/backend/backend.go
- sinks/backend/prometheus/prometheus.go
Resolves #121 
- Create new fields to backend configuration 
- Remove content type validation to GET requests
> feat(sink): create new config fields to available backends

- docker/nginx/nginx-key.conf
> consistent endpoints for backend with /api/v1 prefix

- ui/src/app/common/services/sinks/sink.settings.ts
- ui/src/app/pages/sinks/add/sinks.add.component.html
- ui/src/app/pages/sinks/add/sinks.add.component.ts
- ui/src/app/pages/sinks/delete/sinks.delete.component.html
- ui/src/app/pages/sinks/delete/sinks.delete.component.ts
- ui/src/app/pages/sinks/sinks.component.html
- ui/src/app/pages/sinks/sinks.component.ts
- ui/src/app/shared/components/table/table.component.html
- ui/src/assets/text/strings.ts
Fix many issues on `Sink#Edit` issues, namely:
* define object for sink's backend types
* not being able to edit a sink without creating a new one
* not filling in the fields when editing
Close #139 
Close #140 
Close #141
> bugfix(orb#141): UI sink edit

- ui/src/app/pages/sinks/delete/sinks.delete.component.html
- ui/src/app/pages/sinks/delete/sinks.delete.component.ts
* Fix Sink being deleted even when modal is just closed.
#143
> bugfix(orb-ui sink#delete): Fix Sink Delete on Modal being closed

- ui/src/app/pages/sinks/add/sinks.add.component.html
- ui/src/app/pages/sinks/add/sinks.add.component.ts
- ui/src/app/pages/sinks/delete/sinks.delete.component.html
- ui/src/app/pages/sinks/delete/sinks.delete.component.ts
- ui/src/app/pages/sinks/sinks.component.html
- ui/src/app/pages/sinks/sinks.component.ts
- ui/src/app/shared/components/table/table.component.html
- ui/src/assets/text/strings.ts
Fix minor cosmetic issues on `sinks#list` and `sink#add` components.
* Fix show backend type on list
* Fix titlecase for backend type strings on display on `#list` and `#add`
Closes #124
> bugfix(orb#124): backend type sink

- fleet/backend/pktvisor/handlers.json
- fleet/backend/pktvisor/inputs.json
add static json to represent initial inputs and handlers for /agents/backends/pkvisor/inputs and /agents/backends/pktvisor/handlers endpoints
> static json for pktvisor agent backend reflection

- ui/src/app/pages/fleet/agents/details/agent.details.component.html
- ui/src/app/pages/pages-routing.module.ts
Add Agent Details Page
Closes #199
> feat(orb-ui): agent details page

- ui/src/app/pages/fleet/agents/add/agent.add.component.html
- ui/src/app/pages/fleet/agents/add/agent.add.component.ts
Add Agent Add Page
Location field is extracted and set to orb_tags['location'] upon creation and edition
Inherited tags are still not being displayed
> wip - feat(orb-ui): Agent Add Page

- ui/src/app/pages/sinks/add/sink.add.component.ts
Fixes a few issues that have been introduced with the new routing in place.
*Fix routing from and to edit sink page.
*Fix agent fetch and form control patchData
Closes #140
> fix(orb-ui orb-sinks): Fix #140 - unable to edit sink.

- ui/src/app/pages/fleet/agents/add/agent.add.component.html
- ui/src/app/pages/fleet/agents/add/agent.add.component.ts
Fix page not rendering because wrong attribute value when rendering template.
Fix Matchiplist error for orb_tags on Update
Add Agent Update Page
closes #200
> feat(orb-ui orb-agent): Add Agent Add & Update Page

- ui/src/app/pages/fleet/agents/details/agent.details.component.html
Use this page until new design is implemented.
Agent Details Page from next sprint in usable state.
Design and CSS fixes will come later.
#closes #238
> feat(orb-ui): Create temporary Agent Details Page

- ui/src/assets/text/strings.ts
> fix: description message

- ui/mock-json-server/mock/sink-management-crud.js
- ui/src/app/common/interfaces/orb/sink.interface.ts
- ui/src/app/pages/fleet/agents/list/agent.list.component.ts
- ui/src/app/pages/fleet/groups/list/agent.group.list.component.ts
- ui/src/app/pages/sinks/list/sink.list.component.html
- ui/src/app/pages/sinks/list/sink.list.component.ts
- ui/src/app/shared/components/table/table.component.html
- ui/src/assets/text/strings.ts
BREAKING CHANGE: [sink.interface.ts](ui/src/app/common/interfaces/orb/sink.interface.ts) `sink.status` -> `sink.state`
> refactor!(orb-ui orb-sinks): Refactor Sink interface `status` property.

- ui/src/app/@theme/styles/orb/ngx-datatable/ngx-datatable.scss
- ui/src/app/pages/fleet/agents/add/agent.add.component.html
- ui/src/app/pages/fleet/agents/add/agent.add.component.scss
- ui/src/app/pages/fleet/agents/details/agent.details.component.html
- ui/src/app/pages/fleet/agents/list/agent.list.component.html
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.html
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.scss
- ui/src/app/pages/fleet/groups/details/agent.group.details.component.html
- ui/src/app/pages/fleet/groups/list/agent.group.list.component.html
- ui/src/app/pages/sinks/add/sink.add.component.html
- ui/src/app/pages/sinks/add/sink.add.component.scss
- ui/src/app/pages/sinks/details/sink.details.component.html
- ui/src/app/pages/sinks/list/sink.list.component.html
- ui/src/app/shared/pipes/tagchip.pipe.ts
- ui/src/app/shared/shared.module.ts
- Add algorithmically tags matching colors
> feat: add tags matching colors

- ui/src/app/common/interfaces/orb/agent.policy.interface.ts
- ui/src/app/common/interfaces/orb/dataset.interface.ts
Add interface for Policy
Add interface for Dataset
> feat(orb-ui): Add Policy and Dataset Data Model interface

- ui/src/app/pages/fleet/agents/list/agent.list.component.scss
- ui/src/app/pages/fleet/groups/list/agent.group.list.component.scss
- ui/src/app/pages/sinks/list/sink.list.component.scss
CSS for navigation links in breadcrumb component now has same color as figma design
> feat(orb-ui): change css for breadcrumb navigation links

- ui/src/app/pages/sinks/add/sink.add.component.ts
- ui/src/app/pages/sinks/list/sink.list.component.ts
> fix(orb-ui): Sink Edit success message

- ui/src/app/common/interfaces/orb/agent.interface.ts
- ui/src/app/pages/fleet/agents/list/agent.list.component.html
- ui/src/app/pages/fleet/agents/list/agent.list.component.ts
- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.scss
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
- ui/src/app/pages/pages-routing.module.ts
- ui/src/app/pages/pages.module.ts
Add Agent View Details Page
Closes #264
> feat: add agent view page

- ui/src/app/pages/pages-menu.ts
- ui/src/app/pages/pages.module.ts
- ui/src/app/pages/sinks/add/sink.add.component.html
- ui/src/app/pages/sinks/details/sink.details.component.html
- ui/src/assets/text/strings.ts
fix: bugs #113 #305 #308 #311 #262
closes #113 #305 #308 #311 #262
> fix(orb-ui): bugs #113 #305 #308 #311 #262

- ui/src/app/common/services/agents/agent.groups.service.ts
- ui/src/app/pages/fleet/agents/match/agent.match.component.html
- ui/src/app/pages/fleet/agents/match/agent.match.component.scss
- ui/src/app/pages/fleet/agents/match/agent.match.component.ts
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.html
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.ts
- ui/src/app/pages/fleet/groups/details/agent.group.details.component.html
- ui/src/app/pages/pages.module.ts
- ui/src/assets/text/strings.ts
fix: bugs #324 #323 #322 #316 #315 #314 #313
Closes #324 #323 #322 #316 #315 #314 #313
> fix(orb-ui): bugs #324 #323 #322 #316 #315 #314 #313

- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
> fix(orb-ui): agent view

- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.ts
Disable route to Create | Update Agent Policies until it is fully implemented and functional
> fix(orb-ui): disable agent policy add/update

- ui/src/app/pages/dashboard/dashboard.component.html
- ui/src/app/pages/dashboard/dashboard.component.scss
- ui/src/app/pages/dashboard/dashboard.module.ts
- ui/src/app/pages/pages-routing.module.ts
Add empty Orb homepage with breadcrumb and title
> feat(orb-ui): add orb homepage

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
- ui/src/app/pages/fleet/agents/add/agent.add.component.ts
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.ts
- ui/src/app/pages/sinks/add/sink.add.component.ts
Refactored `'^[a-zA-Z_:][a-zA-Z0-9_]*$'` to `'^[a-zA-Z_][a-zA-Z0-9_-]*$'` pattern
Closes #232
> fix(orb-ui): #232 fix input validator for field name

- ui/src/app/pages/fleet/agents/add/agent.add.component.html
Add 'New Agent', 'Edit Agent' headers for pages of agent creation and update.
Apply code formating to whole page
Closes #317
> fix(orb-ui): #317 agent create|update no header in page

- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.ts
Disable button since feature is not implemented yet
Closes #321
> fix(orb-ui): #321 disable view button for agent policy

- ui/src/app/common/services/agents/agent.groups.service.ts
- ui/src/app/common/services/agents/agent.policies.service.ts
- ui/src/app/common/services/agents/agents.service.ts
- ui/src/app/common/services/sinks/sinks.service.ts
- ui/src/app/pages/fleet/agents/list/agent.list.component.ts
Test removing from cache, since there is 500ms debounce for retrieval of such lists.
Closes #302
Closes #312
Closes #319
> fix(orb-ui): start fixing datatables refresh on edit, create, delete

- agent/docker/orb-agent-entry.sh
By setting environment variable `PKTVISOR_PCAP_IFACE_DEFAULT` to `mock`
> add option to mock agent traffic 

- ui/src/app/pages/fleet/agents/key/agent.key.component.ts
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
closes #418 
Fix agent provisioning command
> fix(orb-ui): fix agent provisioning command

- ui/src/app/pages/fleet/agents/key/agent.key.component.html
- ui/src/app/pages/fleet/agents/key/agent.key.component.scss
- ui/src/app/pages/fleet/agents/key/agent.key.component.ts
- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
> fix(orb-ui): change to ETH-INTERFACE to mock

- ui/src/app/common/services/agents/agent.policies.service.ts
- ui/src/environments/environment.defaults.ts
Closes #429 
@dscabral This enables service communication and removes mocked data
> fix(orb-ui): enable production service routes, remove mocked object data

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
> fix: #369 align handler add button

- ui/src/app/pages/login/login.component.html
- ui/src/assets/text/strings.ts
> feature: #425 add orb link to login page

- ui/src/app/pages/fleet/agents/add/agent.add.component.ts
> feature: show toast message with agent key modal

- ui/src/app/pages/datasets/list/dataset.list.component.ts
> fix: remove dataset dates related comlumns

- policies/api/http/responses.go
> hotfix(policies) change policy_id to agent_policy_id

- fleet/backend/pktvisor/pktvisor.go
> hotfix(fleet):lower case backends json keys

- ui/src/app/pages/datasets/add/dataset.add.component.html
- ui/src/app/pages/datasets/add/dataset.add.component.ts
> fix(orb-ui): fix dataset stepper controls on edit/create

- agent/rpc_from.go
- fleet/agents.go
- fleet/comms.go
- fleet/comms_rpc.go
- fleet/mocks/comms.go
- fleet/postgres/agents.go
- fleet/postgres/init.go
- go.mod
- go.sum
- version.go
> feat(agent) Create version check for too old agents

- fleet/api/http/openapi.yaml
add routes:
- /agents/backends/agents 
- /agents/backends/pktvisor/taps 
- /agents/backends/pktvisor/inputs 
- /agents/backends/pktvisor/handlers 
- /agents/backends/{backend}/
> doc(fleet): openapi spec update

- ui/src/app/pages/register/register.component.html
> fix: #482 register page description

- docker/docker-compose.yml
Fix docker-compose.yml ui target image tag from 'latest'… to env
Resolves #501
> fix(orb-ui): Fix docker-compose.yml 

- policies/api/http/endpoint.go
> hotfix(policies): Fix valid field always with false

- ui/src/app/pages/datasets/add/dataset.add.component.html
- ui/src/app/pages/datasets/add/dataset.add.component.ts
- ui/src/app/pages/datasets/details/dataset.details.component.html
- ui/src/app/pages/datasets/list/dataset.list.component.ts
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/details/agent.policy.details.component.html
- ui/src/app/pages/fleet/agents/list/agent.list.component.html
- ui/src/app/pages/fleet/groups/details/agent.group.details.component.html
- ui/src/app/pages/sinks/add/sink.add.component.html
- ui/src/app/pages/sinks/details/sink.details.component.html
Closes: #488 #486 #491 #476 #494 #470 #471 #495 #472
> fix: minor ui adjustments

- ui/src/app/common/interfaces/orb/policy/policy.tap.interface.ts
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
resolves #503 
Add filter options to agent policy configuration wizard
> fix(orb-ui): add agent policy filter config options

- ui/src/app/pages/fleet/agents/list/agent.list.component.html
> fix(orb-ui): remove regions text

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
> fix(orb-ui): #485 'save' instead of 'next'

- ui/src/app/@core/core.module.ts
- ui/src/app/pages/register/register.component.html
- ui/src/app/pages/register/register.component.ts
resolves #528 add company name field to register page
> fix(orb-ui): #528 add company name field to register page

- ui/src/app/auth/auth.module.ts
- ui/src/app/auth/auth.routing.module.ts
- ui/src/app/pages/login/request-password.component.html
- ui/src/app/pages/login/request-password.component.scss
- ui/src/app/pages/login/request-password.component.ts
- ui/src/app/pages/pages.module.ts
> feat(orb-ui): add style to forgot-password page

- fleet/api/http/openapi.yaml
Resolves #534
- add key and channel id to Agent object schema
- add response schema of agent group validate
> doc(fleet): update fleet service openapi spec

- docker/templates/users.tmpl
Check [this website](https://www.socketloop.com/tutorials/golang-how-to-pass-map-to-html-template-and-access-the-map-s-element) to understand how `{{ index .myVar <position> }}` works.
> Fixed recipient value in the password recovery email template

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
fix: add filter options to handler configuration page.
> fix(orb-ui): #579 handlers filters

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
Suggest sequential name for handler based on type
> feat(orb-ui): #507 UI handler name template

- ui/src/app/common/services/agents/agent.groups.service.ts
- ui/src/app/common/services/agents/agent.policies.service.ts
- ui/src/app/common/services/agents/agents.service.ts
- ui/src/app/common/services/dataset/dataset.policies.service.ts
- ui/src/app/common/services/sinks/sinks.service.ts
- ui/src/app/pages/datasets/list/dataset.list.component.ts
- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.ts
- ui/src/app/pages/fleet/agents/list/agent.list.component.ts
- ui/src/app/pages/fleet/groups/list/agent.group.list.component.ts
- ui/src/app/pages/sinks/list/sink.list.component.ts
fix(orb-ui): pages never stop reloading
* fix for agent groups list page
* fix for agents list page
* fix for datasets list page
* fix for agent policies list page
> fix(orb-ui): #362 UI reload incomplete

- sinks/api/http/endpoint.go
- sinks/api/http/endpoint_test.go
> fix(sinks): fix status code response of sink ceration

- ui/src/app/pages/fleet/agents/add/agent.add.component.html
- ui/src/app/pages/fleet/agents/details/agent.details.component.html
Remove red asterisk '*' required tags for agents in view… and details page
#613
> fix(orb-ui): #613 agent tags not required

- ui/src/app/pages/datasets/add/dataset.add.component.html
- ui/src/app/pages/datasets/details/dataset.details.component.html
#622
fix displaying dataset tags since dataset tags no longer supported
> fix(orb-ui): #622 dataset details view

- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
fix agent view copy command button not changing icon after click
#612
> fix(orb-ui): #612 fix agent view copy command button

- ui/src/app/pages/pages-menu.ts
#624 - in navigation menu, fix menu items order
> fix(orb-ui): #624 fix menu items order

- ui/src/app/pages/fleet/groups/add/agent.group.add.component.ts
#617 Fix agent group creation screen not displaying agent matches.
> fix(orb-ui): #617 agent group creation agent matches

- ui/src/app/pages/datasets/policies.agent/details/agent.policy.details.component.html
#619 Remove required asterisk '*' from version field in agent policy detail view
> fix(orb-ui): #619 agent policy detail view version required asterisk

- ui/src/app/common/services/agents/agents.service.ts
fix #609 showing error message when no error present
> fix(orb-ui): fix error msg

- ui/src/app/pages/fleet/groups/details/agent.group.details.component.html
Fix agent tag display on agent group details view. #615
> fix(orb-ui): fix display of agent tags on agent group details view

- ui/src/app/pages/dashboard/dashboard.component.html
#625 Fix order of items on dashboard page
> fix(orb-ui): #625 fix order on dashboard page

- ui/src/app/pages/dashboard/dashboard.component.html
Improves home page action card ordering for user actions.
#657
> enhancement(orb-ui): #657 improve home page card ordering for user actions

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.scss
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
fix(orb-ui): remove option to choose backend type for agent policy
fix(orb-ui): tap & input of agent policy 
fix(orb-ui): fix handler configuration json not being posted
> fix(orb-ui): Agent Policy Fixes

- ui/src/app/pages/fleet/agents/key/agent.key.component.html
- ui/src/app/pages/fleet/agents/key/agent.key.component.scss
- ui/src/app/pages/fleet/agents/key/agent.key.component.ts
- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.scss
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
mark text where user could/should change interface
> feat(orb-ui): #641 change color of 'mock' string

- sinks/api/http/endpoint.go
- sinks/api/http/endpoint_test.go
- sinks/postgres/sinks.go
- sinks/postgres/sinks_test.go
- sinks/sinks_service.go
- sinks/sinks_service_test.go
Create more unit tests and add some minor improvements to the source code
Resolves #654
> Increase sinks service unit tests coverage

- agent/backend/pktvisor/pktvisor.go
- agent/policyMgr/manager.go
* Create a manual retry to pktvisor request webservice
* Call the remove policy function for the local repo from orb-agent
> Orb-agent heartbeat bug (Removed policies remain with running state)

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.scss
- ui/src/app/pages/pages.module.ts
- ui/src/app/shared/pipes/advanced-options.pipe.ts
- ui/src/app/shared/shared.module.ts
Add advanced options to configuration and filter options for taps/inputs in agent policies page. Resolves #644
> feat(orb-ui): #644 add advanced options agent policies configuration

- python-test/features/steps/control_plane_agents.py
- python-test/features/steps/local_agent.py
- python-test/features/steps/test_config.py
Ignore_certificate_errors - This things I tested and discussed with Stefano before, and by some mistake I didn't commit it.
> recovering some changes that I noticed that should be on previous PR

- ui/src/app/pages/request-password/request-password.component.html
- ui/src/app/pages/request-password/request-password.component.ts
- ui/src/app/pages/reset-password/reset-password.component.ts
fix(orb-ui): override nbResetPassword resetPassword method
fix(orb-ui): fix button outside form scope not submitting forgotPassword
> fix(orb-ui): #525 forgot password page

- ui/src/app/common/services/agents/agent.groups.service.ts
- ui/src/app/common/services/agents/agent.policies.service.ts
- ui/src/app/common/services/dataset/dataset.policies.service.ts
- ui/src/app/pages/datasets/details/dataset.details.component.html
- ui/src/app/pages/datasets/details/dataset.details.component.ts
- ui/src/app/pages/datasets/list/dataset.list.component.ts
> fix(orb-ui): #692 Dataset View

- ui/src/app/pages/datasets/list/dataset.list.component.ts
Remove option to filter dataset by tags.
Fixes #473
> fix(orb-ui): remove option to filter dataset by tags

- ui/src/app/pages/datasets/policies.agent/details/agent.policy.details.component.html
- ui/src/app/pages/datasets/policies.agent/details/agent.policy.details.component.scss
- ui/src/app/pages/datasets/policies.agent/details/agent.policy.details.component.ts
* Add section input type and tap names 
* Add section for listing of handlers names
Resolves #695
> fix(orb-ui): Policy Details View

- ui/src/app/app.module.ts
- ui/src/app/auth/auth.module.ts
- ui/src/app/pages/register/register.component.html
- ui/src/app/pages/register/register.component.ts
Fix for pactsafe on --prod
@manrodrigues try and set `
PS_GROUP_KEY=group-rkjy8a9uy
` on ui/.env file
> fix(orb-ui): #737 register button not working

- ui/src/app/@core/core.module.ts
- ui/src/app/pages/register/register.component.ts
* authentication module no longer expects valid token on /users endpoint
* remove code for redirection on /users endpoint response - force auth
> fix(orb-ui): fix error message during register

- agent/agent.go
- agent/backend/pktvisor/pktvisor.go
- agent/comms.go
- agent/logging.go
- agent/policyMgr/manager.go
- cmd/agent/main.go
Remove retry on pktvisor request
Create more wrappers for errors messages related to mqtt errors
Show orb-agent version on start up
> refactor(orb-agent): enhancement on log messages

- python-test/features/login.feature
I noticed there were two duplicate tests on login feature
> removing duplicated tests

- python-test/features/integration.feature
- python-test/features/steps/control_plane_agent_groups.py
- python-test/features/steps/control_plane_agents.py
- python-test/features/steps/control_plane_datasets.py
- python-test/features/steps/control_plane_policies.py
- python-test/features/steps/control_plane_sink.py
- python-test/features/steps/utils.py
- Check if sink with invalid credentials becomes active
- Provision agent after group (check if agent subscribes to the group) 
- Provision agent with tag matching existing group linked to a valid dataset
> automated tests: covering integration scenarios

- ui/src/app/shared/pipes/advanced-options.pipe.ts
* fix filter advancedOptions, enabling correct rendering of advanced and non-advanced options for agent policies
> fix(orb-ui): fix advancedOptions filter

- python-test/docs/agents/run_two_orb_agents_on_different_ports.md
- python-test/docs/agents/run_two_orb_agents_on_the_same_port.md
- python-test/docs/development_guide.md
- python-test/docs/index.md
- python-test/docs/sanity.md
- python-test/docs/smoke.md
- python-test/features/agentProviderUi.feature
- python-test/features/agentsProvider.feature
- python-test/features/environment.py
- python-test/features/integration.feature
- python-test/features/steps/control_agents_ui.py
- python-test/features/steps/control_plane_agents.py
- python-test/features/steps/local_agent.py
- python-test/features/steps/login_ui.py
- run_two_orb_agents_on_different_ports
- run_two_orb_agents_on_the_same_port
> Tests - set pktvisor port test

- ui/src/app/pages/fleet/agents/key/agent.key.component.ts
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
* agent provisioning command to use 'develop' tagged docker image `ns1labs/orb-agent:develop`
> fix(orb-ui): agent provisioning command image tag

- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.ts
* fix last modified date on agent policy list
> fix(orb-ui): #487 last modified field on policies list page

- ui/src/app/pages/register/register.component.html
* fix register form fullname field regex pattern
`^([a-zA-Z]+)\s([a-zA-Z ]+)$`
> fix(orb-ui): fix regex pattern for fullname in register form

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
fix wrong databinding that breaks editing an agent policy.
#793
> fix(orb-ui): fix agent policy edit failing

- ui/src/app/pages/datasets/add/dataset.add.component.html
- ui/src/app/pages/datasets/add/dataset.add.component.ts
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
- ui/src/app/pages/fleet/agents/add/agent.add.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.html
- ui/src/app/pages/sinks/add/sink.add.component.html
* Agent Create/Edit
* Agent Group/Edit
* Agent Policy Create/Edit
* Dataset Create/Edit
* Sink Create/Edit
> fix(orb-ui): Add cancel button to all stepper controls in forms

- ui/src/app/common/interfaces/orb/agent.interface.ts
- ui/src/app/common/services/agents/agents.service.ts
- ui/src/app/pages/fleet/agents/list/agent.list.component.scss
- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.scss
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
- ui/src/app/shared/pipes/pretty-json.pipe.ts
- ui/src/app/shared/shared.module.ts
* new header section for agent view
* add agent capabilities list
* update tags display
* update provisioning command card
* update policy/datasets card
* update group name list card
> feat(orb-ui): Agent View Enhancements

- ui/src/app/pages/fleet/groups/add/agent.group.add.component.html
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.scss
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.ts
* Fix status color for matching agent list
* Fix date format for last activity
> fix(orb-ui): agent group add page matching agents table status

- ui/src/app/@theme/styles/themes.scss
- ui/src/app/pages/datasets/add/dataset.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/fleet/agents/add/agent.add.component.html
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.html
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.scss
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.ts
- ui/src/app/pages/sinks/add/sink.add.component.html
- ui/src/app/styles/mainflux.scss
1920x1080 & 1366x768
*fix issue update matching tags breaks table column configuration
*fix issue update matching tags breaks rows - change detection not enabled.
> fix(orb-ui): agent group matching agents list issues

- ui/src/app/pages/register/register.component.ts
* fix typo in first name split
* fix _ps becoming undefined on page refresh
* fix submit register action not redirecting to dashboard
> fix(orb-ui): register redirect issue

- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.html
- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.ts
* add N/A and tooltip for policies that do not have version property defined yet
* show correct property 'version' on agent policies list page
> fix(orb-ui): fix correct prop tracking 'version'

- ui/src/app/pages/fleet/agents/list/agent.list.component.ts
- ui/src/app/pages/fleet/agents/match/agent.match.component.ts
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.ts
- ui/src/app/pages/fleet/groups/list/agent.group.list.component.ts
- ui/src/app/pages/sinks/list/sink.list.component.ts
* fix order by matching agents in agent group list page
* add custom comparator to orb tags
> fix(orb-ui): define custom tag comparator for ngx-datatables

- sinker/redis/consumer/streams.go
- sinks/api/http/endpoint.go
- sinks/api/http/logging.go
- sinks/api/http/metrics.go
- sinks/redis/producer/streams.go
- sinks/sinks.go
- sinks/sinks_service.go
- sinks/sinks_service_test.go
Change the update signature to return a Sink
On Redis stream middleware, create a defer function to get the owner id on the update function and send it to the Sinker service
> Bug missing owner_id redis sinker update

- ui/src/app/pages/register/register.component.ts
* fix add metadata with fullName and company
* verify that _ps is available and if not, ignore calls
> fix(orb-ui): fullName and company not sent on register

- ui/src/app/pages/datasets/details/dataset.details.component.ts
* method for retrieving sinks not updated after sinkService refactor.
> fix(orb-ui): fix broken dataset details view

- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
fix(orb-ui): fix agent view datasets showing in wrong policy nest
> fix(orb-ui): fix agent view datasets showing in wrong policy nest

- ui/src/app/pages/fleet/agents/key/agent.key.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
change provisioning command AGENT KEY string and
add informative text
> fix(orb-ui): agent provisioning text

- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.html
> fix(orb-ui): add information text for total of policies

- ui/src/app/pages/datasets/add/dataset.add.component.html
- ui/src/app/pages/datasets/add/dataset.add.component.scss
- ui/src/app/pages/datasets/add/dataset.add.component.ts
* fix add sink button placement css
* fix css styling of sink display on *sink selection step*
* fix css styling display of sink list on *final step - review*
> fix dataset sink list display style

- ui/src/app/shared/components/orb/agent/groups/agent-groups.component.html
- ui/src/app/shared/components/orb/agent/groups/agent-groups.component.ts
- ui/src/app/shared/components/orb/agent/information/agent-information.component.html
- ui/src/app/shared/components/orb/agent/policies-datasets/agent-policies-datasets.component.html
- ui/src/app/shared/components/orb/agent/policies-datasets/agent-policies-datasets.component.ts
* better error handling and more resilient agent view page
> fix(orb-ui): more resilient agent view page

- ui/src/app/pages/fleet/groups/add/agent.group.add.component.html
* Fix code for matching tags mistakenly removed.
* Fix second step button type, now moving to third step correctly.
> fix(orb-ui): agent group match not showing in screen

- ui/src/app/common/interfaces/orb/agent.interface.ts
- ui/src/app/shared/components/orb/agent/policies-datasets/agent-policies-datasets.component.html
- ui/src/app/shared/components/orb/agent/policies-datasets/agent-policies-datasets.component.scss
- ui/src/app/shared/components/orb/agent/policies-datasets/agent-policies-datasets.component.ts
* show error message when policy status === failed_to_apply
* add css improvements
> fix(orb-ui): agent view policy status

- ui/src/app/shared/components/orb/agent/groups/agent-groups.component.html
- ui/src/app/shared/components/orb/agent/groups/agent-groups.component.scss
* fix agent group item styling for agent groups section of agent view
> fix(orb-ui): agent view group listing css

- ui/src/app/common/services/agents/agent.groups.service.ts
- ui/src/app/common/services/agents/agent.policies.service.ts
- ui/src/app/common/services/sinks/sinks.service.ts
- ui/src/app/pages/datasets/details/dataset.details.component.html
- ui/src/app/pages/datasets/details/dataset.details.component.ts
- ui/src/app/shared/components/orb/sink/sink-display/sink-display.component.html
- ui/src/app/shared/components/orb/sink/sink-display/sink-display.component.scss
- ui/src/app/shared/components/orb/sink/sink-display/sink-display.component.ts
- ui/src/app/shared/shared.module.ts
* add message for non-retrievable entities - agent group, agent policy, sink;
* fix requests failing on error since forkjoin quits on error - adjust services accordingly
> orb(ui): fix dataset details modal failed state

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
> fix(orb-ui): fix yaml policy example

- ui/src/app/common/services/agents/agent.groups.service.ts
- ui/src/app/common/services/agents/agent.policies.service.ts
- ui/src/app/common/services/agents/agents.service.ts
- ui/src/app/common/services/dataset/dataset.policies.service.ts
- ui/src/app/common/services/fleets/fleets.service.ts
- ui/src/app/common/services/sinks/sinks.service.ts
- ui/src/app/common/services/users/groups.service.ts
* Fix faulty pagination logic, leading to 'extra' items in the list
* agents service
* agent groups service
* agent policies service
* datasets service
* sinks service
> fix(orb-ui): #957 orb pagination

- ui/src/app/shared/components/orb/agent/agent-groups/agent-groups.component.scss
- ui/src/app/shared/components/orb/agent/agent-groups/agent-groups.component.ts
- ui/src/app/shared/components/orb/agent/agent-provisioning/agent-provisioning.component.html
- ui/src/app/shared/components/orb/policy/policy-datasets/policy-datasets.component.ts
- ui/src/app/shared/components/orb/policy/policy-details/policy-details.component.html
* fix agent group item color and font
* fix agent provisioning button click event handler
* remove agent policy view dataset component for now
* change field name to Policy Name in Agent Policy View
* change page title in agent policy view
* fix edit agent group not openining from details modal when opened from agent or policy view pages
> fix(orb-ui): general fixes to agent and policy view components

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
> fix(orb-ui): #997 agent policy yaml editing

- ui/src/app/pages/datasets/details/dataset.details.component.html
> fix(orb-ui): improve failed to fetch message

- ui/src/app/common/services/agents/agents.service.ts
- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.scss
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
* add button to reset agent to agent view page
> feat(orb-ui): added agent reset button

- ui/src/app/pages/datasets/list/dataset.list.component.ts
- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.ts
- ui/src/app/pages/fleet/agents/list/agent.list.component.ts
- ui/src/app/pages/fleet/groups/list/agent.group.list.component.ts
- ui/src/app/pages/sinks/list/sink.list.component.ts
* use correct method to retrieve all items of list.
> fix(orb-ui): #362 lists are not properly refreshed after item deletion

- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.html
* fix agent policy view page title <Agent View> to <Policy View>
> hotfix(orb-ui): Change Agent Policy View page title

- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.scss
- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.html
- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.scss
- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.ts
** please note the error on agent groups displaying htmlerror as a group should be fixed in another pr
** relates to now closed #956
> hotfix(orb-ui): change agent reset button placement

- ui/src/app/common/interfaces/orb/orb.entity.interface.ts
- ui/src/app/common/services/agents/agent.groups.service.ts
- ui/src/app/shared/components/orb/agent/agent-groups/agent-groups.component.html
- ui/src/app/shared/components/orb/agent/agent-groups/agent-groups.component.scss
- ui/src/app/shared/components/orb/agent/agent-groups/agent-groups.component.ts
- ui/src/app/shared/components/orb/agent/agent-policies-datasets/agent-policies-datasets.component.html
- ui/src/app/shared/components/orb/agent/agent-policies-datasets/agent-policies-datasets.component.scss
@manrodrigues I haven't created an issue for this, but is related to comments on other issues and PRs, I'm not sure if should track on own issue.
> hotfix(orb-ui): improvements on agent view page css and error messages

- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.html
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.html
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.scss
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.ts
- ui/src/app/shared/shared.module.ts
* add agent group section to policy view page
> feat(orb-ui): #985 agent policy groups

- ui/src/app/pages/datasets/list/dataset.list.component.ts
- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.ts
- ui/src/app/pages/fleet/agents/list/agent.list.component.ts
- ui/src/app/pages/fleet/groups/list/agent.group.list.component.ts
- ui/src/app/pages/pages.module.ts
- ui/src/app/pages/sinks/list/sink.list.component.ts
* force clean cache on every item operation on list-like pages.
> hotfix(orb-ui): #362 force clean cache on every operation

- ui/src/app/pages/pages-menu.ts
* remove dataset menu item
Datasat now acessible via Agent Policy View only.
> feat(orb-ui): Remove Dataset menu item

- python-test/Makefile
adds a makefile for testing with multiple formats of reports for behave
this will enable automated tests to use makefile and provide reports after execution
> chore(python-test): add a makefile for testing

- ui/src/app/pages/datasets/dataset-from/dataset-from.component.html
- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.html
- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.scss
- ui/src/app/shared/components/orb/policy/policy-datasets/policy-datasets.component.html
- ui/src/app/shared/components/orb/policy/policy-datasets/policy-datasets.component.scss
* fix(orb-ui): #1117 fix button title '+ new dataset'
* fix(orb-ui): remove letter g from dataset-from component
* fix(orb-ui): #1116 #1084 mouse cursor for elements that are clickable
> fix(orb-ui): Policy View text button

- ui/src/app/pages/datasets/policies.agent/delete/agent.policy.delete.component.html
Add warning text for removal of policy. Related datasets will also be removed.
> hotfix(orb-ui): add warning message for related datasets to be removed.

- ui/src/app/pages/datasets/dataset-from/dataset-from.component.html
- ui/src/app/pages/datasets/dataset-from/dataset-from.component.ts
- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.ts
- ui/src/app/shared/components/orb/sink-control/sink-control.component.html
- ui/src/app/shared/components/orb/sink-control/sink-control.component.ts
- ui/src/app/shared/components/orb/sink-display/sink-display.component.html
- ui/src/app/shared/components/orb/sink-display/sink-display.component.ts
user was not able to add a sink that has been already added and removed.
user was not able to remove a sink.
> fix(orb-ui): #1110 #1144 fix sink control on dataset-from component.

- ui/src/app/pages/pages-menu.ts
> fix(orb-ui): #1137 remove entry from navbar

- ui/src/app/pages/pages-routing.module.ts
hotfix(orb-ui): remove breadcrumb and nested routing of 
* fleet management
* dataset explorer
> hotfix(orb-ui): fleet breadcrumb removal

- .github/workflows/go-develop.yml
This fix the action to build the packages but not pushes them to docker on PRs
> ci(build): fix the ifs to build but not push the image on pull_request.

- .github/workflows/go-production.yml
- Makefile
This PR fixes ci for production when we dont have arguments being passed to makefile
> [FIX] fix-ci

- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-stg.yml
- .github/workflows/go-production.yml
New GitHub Action with the deployment manual or merge to staging
> ci(build): test new ci to deploy to staging

- .idea/runConfigurations/agent_group.xml
- .idea/runConfigurations/agent_provider.xml
- .idea/runConfigurations/all_tests.xml
- .idea/runConfigurations/datasets.xml
- .idea/runConfigurations/int_tests.xml
- .idea/runConfigurations/login.xml
- .idea/runConfigurations/pktvisor.xml
- .idea/runConfigurations/policies.xml
- .idea/runConfigurations/sink.xml
- .idea/runConfigurations/ui_tests.xml
Adding the test project configuration
> intellij project configs

- .github/workflows/go-develop.yml
- .github/workflows/go-production.yml
Add buildx on orb-agent to produce images for some architectures when merge on production branch
> [FIX] add buildx production pipeline

- ui/src/app/common/services/agents/agent.policies.service.ts
- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.html
- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.scss
- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.ts
> feat(orb-ui): duplicate policy button

- .github/workflows/go-develop.yml
- .github/workflows/go-main.yml
- .github/workflows/go-production.yml
This PR remove condition pro build agent docker images. We always need to build when we have changes on branch to guarantee new agent version
> [FIX] agent build image

- ui/src/app/pages/fleet/agents/details/agent.details.component.html
- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.html
fix(orb-ui): #1216 agent view/list show unique tags (orb_tags, agent_tags).
> fix(orb-ui): #1216 agent view/list show unique tags

- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.html
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.ts
fix(orb-ui): add material tooltip & remove dead code from agent policy view
> fix(orb-ui): add material tooltip #1173

- ui/src/app/common/services/agents/agents.service.ts
- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.html
- ui/src/app/pages/fleet/agents/add/agent.add.component.ts
- ui/src/app/pages/fleet/agents/details/agent.details.component.html
- ui/src/app/pages/fleet/agents/list/agent.list.component.html
- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.html
- ui/src/app/shared/components/orb/combined-tag/combined-tag.component.html
- ui/src/app/shared/components/orb/combined-tag/combined-tag.component.scss
- ui/src/app/shared/components/orb/combined-tag/combined-tag.component.ts
- ui/src/app/shared/shared.module.ts
fix(orb-ui): not showing agent tags on agent view
fix(orb-ui): replace agent details modal -> agent view page
feat(orb-ui): mock attempt agent tags
> feat(orb-ui): #1242 UI agent tag style

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
hotfix(orb-ui): add callback to 'Cancel' button allowing user to navigate back.
> hotfix(orb-ui): add callback to 'Cancel' button 

- fleet/postgres/agent_groups.go
- fleet/postgres/agents.go
- policies/api/http/endpoint.go
- policies/api/http/responses.go
This fixes #696 
Agent Groups
Policies
Datasets
> fix(fleet/policies): ensure ts_created is being sent on the requests

- python-test/features/agentGroups.feature
- python-test/features/agentsProvider.feature
- python-test/features/integration.feature
- python-test/features/steps/control_plane_agent_groups.py
- python-test/features/steps/control_plane_agents.py
- python-test/features/steps/control_plane_policies.py
- python-test/features/steps/local_agent.py
- python-test/features/steps/utils.py
- python-test/print_behavex_output.py
When a test scenario fails, the assertion message need to be more helpful to identify the problem.
> improving errors return

- python-test/docs/development_guide.md
- python-test/docs/index.md
- python-test/docs/policies/create_3_duplicated_dns_policy_without_insert_new_name_and_1_with_new_name.md
- python-test/docs/policies/create_4_duplicated_policy_with_new_name.md
- python-test/docs/policies/create_duplicated_dhcp_policy_without_insert_new_name.md
- python-test/docs/policies/create_duplicated_dns_policy_without_insert_new_name.md
- python-test/docs/policies/create_duplicated_net_policy_without_insert_new_name.md
- python-test/docs/sanity.md
- python-test/docs/smoke.md
- python-test/features/policies.feature
- python-test/features/steps/control_plane_policies.py
- python-test/features/steps/local_agent.py
- python-test/features/steps/utils.py
- policies can be duplicated 3 times without insert new policy name
> duplicate policy

- sinker/backend/pktvisor/pktvisor.go
- sinker/backend/pktvisor/pktvisor_test.go
- sinker/backend/pktvisor/types.go
This reverts commit 66fda6de116f81e5cbd08ead399b285559e0fe5c.
> Revert "fixes flow ports and indexes payload"

- sinker/backend/pktvisor/pktvisor.go
- sinker/backend/pktvisor/pktvisor_test.go
- sinker/backend/pktvisor/types.go
also add proper values for flow unit tests
> add new ip_port metrics to flow handler parser

- ui/src/app/pages/datasets/dataset-from/dataset-from.component.html
- ui/src/app/pages/datasets/dataset-from/dataset-from.component.ts
- ui/src/app/pages/pages.module.ts
- ui/src/app/shared/pipes/sort.pipe.ts
- ui/src/app/shared/shared.module.ts
Changes Dataset-From modal component(for create|edit|delete dataset) is Group Selector with
autocomplete/autosuggestion input + selector combination for retrieving desired agent group id.
> feat(orb-ui): #1287 Autocomplete Selector

- ui/src/app/pages/fleet/agents/key/agent.key.component.scss
- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.html
- ui/src/app/shared/components/orb/agent/agent-provisioning/agent-provisioning.component.html
- ui/src/app/shared/components/orb/agent/agent-provisioning/agent-provisioning.component.ts
> fix(orb-ui): #1102 Agent UI css

- .github/workflows/go-develop.yml
- .idea/runConfigurations/docker_fleet__Compose_Deployment.xml
- .idea/runConfigurations/docker_policies__Compose_Deployment.xml
- .idea/runConfigurations/docker_sinker__Compose_Deployment.xml
- .idea/runConfigurations/docker_sinks__Compose_Deployment.xml
- .idea/runConfigurations/docker_ui__Compose_Deployment.xml
- Makefile
This PR add migrate service image being produced by CI workflow
> Add migrate service

- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.html
- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.scss
> fix(orb-ui): #1304 fix css for save/discard buttons

- ui/src/app/pages/fleet/agents/key/agent.key.component.ts
> usual copy icon on agent modal

- .github/workflows/agent.yml
This PR fix agent build with workflow dispatch
> [FIX] agent build

- ui/src/app/pages/fleet/agents/match/agent.match.component.scss
> fix(orb-ui): #1412 - Use pointer cursor on agent names

- python-test/features/environment.py
- python-test/features/integration.feature
- python-test/features/steps/control_plane_agent_groups.py
- python-test/features/steps/control_plane_agents.py
- python-test/features/steps/control_plane_datasets.py
- python-test/features/steps/control_plane_policies.py
- python-test/features/steps/control_plane_sink.py
- python-test/features/steps/local_agent.py
The intent of this PR is to improve the information returned when a test scenario fails
Since the tests are running in the pipeline, the more information that can be shown on the failure cases of a scenario, the better.
> Improving the information returned when a test scenario fails

- ui/src/app/auth/pages/register/register.component.html
- ui/src/app/auth/pages/register/register.component.ts
issue #1403
https://user-images.githubusercontent.com/101733592/177619506-b6559c35-53fd-4b25-a0ad-3c300c0df042.mp4
>  fix(orb-ui): #1403 - Block register button for repeated emails

- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.html
- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.ts
> fix(orb-ui): #1439 - Include backend type and version on agent page

- ui/src/app/pages/fleet/agents/add/agent.add.component.html
> fix(orb-ui): #1395 - Implement agent name error messages

- .github/workflows/go-production.yml
This PR add tag ${{VERSION}}-${{commithash}} on images from production, currently we had just latest tag.
> [FIX] image tags for prod

- agent/backend/pktvisor/pktvisor.go
- agent/comms.go
> Revert "feat(agent): successfully on lost connection restore all subs and policies."

- python-test/features/agentGroups.feature
- python-test/features/agentProviderUi.feature
- python-test/features/agentsProvider.feature
- python-test/features/environment.py
- python-test/features/integration.feature
- python-test/features/sinks.feature
- python-test/features/steps/control_plane_agents.py
- python-test/features/steps/local_agent.py
- python-test/features/steps/utils.py
standardizing log timeout and status and maintaining container when test fails
> standardizing the wait time

- agent/agent.go
- agent/backend/pktvisor/pktvisor.go
- agent/comms.go
- cmd/agent/main.go
This enables the agent to resume the subscriptions fixing the error when disconnecting, we couldn't reach the agent.
Also added more logs and log in debug as JSON format to facilitate to filter and have a unified front for logging in general.
> Resub rollback

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
* buttons within forms assigned type='button' remove error 'no form connected...'
> fix(orb-ui): add policy form issues

- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.ts
* Fix access no undefined property while retrieving backend and backend version from a newly created agent.
> fix(orb-ui): #1456 Agent View Fix

- ui/src/app/@theme/styles/_overrides.scss
- ui/src/app/pages/pages-menu.ts
- ui/src/app/shared/components/orb/agent/agent-policies-datasets/agent-policies-datasets.component.ts
**Issue:** https://github.com/ns1labs/orb/issues/1470
- Changed color while hovering
- Change color for active route
**Before:**
**After:**
> fix(orb-ui): #1491 Change navbar link color while hovering and when route is active

- .github/workflows/go-production.yml
This PR fix slack post message
> fix(ops) slack post message

- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.html
* change agent policy edit to use new view instead of stepper
> feat(orb-ui): #1519 change policy edit from stepper to policy view component

- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.ts
**Issue**: https://github.com/ns1labs/orb/issues/1522
Retrieve current policy state after saving policy configuration.
https://user-images.githubusercontent.com/42921279/180042970-a095c26d-2b5a-49e4-a714-c3c67d5bc878.mp4
> fix(orb-ui): #1522 Retrieve current policy state after saving policy configuration

- ui/proxy-config.json
- ui/src/app/@theme/styles/_overrides.scss
- ui/src/app/common/interfaces/orb/agent.policy.interface.ts
- ui/src/app/common/interfaces/orb/dataset.policy.interface.ts
- ui/src/app/common/services/agents/agent.groups.service.ts
- ui/src/app/common/services/agents/agent.policies.service.ts
- ui/src/app/common/services/agents/agents.service.ts
- ui/src/app/common/services/dataset/dataset.policies.service.ts
- ui/src/app/common/services/orb.service.ts
- ui/src/app/common/services/sinks/sinks.service.ts
- ui/src/app/pages/datasets/add/dataset.add.component.ts
- ui/src/app/pages/datasets/dataset-from/dataset-from.component.ts
- ui/src/app/pages/datasets/list/dataset.list.component.html
- ui/src/app/pages/datasets/list/dataset.list.component.ts
- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.ts
- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.html
- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.ts
- ui/src/app/pages/fleet/agents/list/agent.list.component.ts
- ui/src/app/pages/fleet/groups/list/agent.group.list.component.ts
- ui/src/app/pages/sinks/list/sink.list.component.ts
- ui/src/app/shared/components/orb/policy/policy-datasets/policy-datasets.component.html
- ui/src/app/shared/components/orb/policy/policy-datasets/policy-datasets.component.ts
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.ts
* fixed expand cycle 'dir' param undefined - root cause of issue before deploy
* fixed condition on expand cycle, adopted scan() in favor of reduce()
* fixed keep watching on observable of another page when not needed.
* fixed dataset add component only querying the first 100 items
* fixed group service, group listing page errors
* fixed sink service
* fixed policy service
* fixed dataset service
* fixed agent policy view dataset list
* improved load time for agent policy view
> fix(orb-ui): fix page issues after filter/poll update

- ui/src/app/common/interfaces/orb/agent.interface.ts
- ui/src/app/common/interfaces/orb/agent.policy.interface.ts
- ui/src/app/common/services/agents/agents.service.ts
- ui/src/app/pages/fleet/agents/list/agent.list.component.html
- ui/src/app/pages/fleet/agents/list/agent.list.component.scss
- ui/src/app/pages/fleet/agents/list/agent.list.component.ts
* add column showing aggregate state of agent's policies if any.
* add option to filter agent by policies aggregate state.
> feat(orb-ui): #1347 agent view policy column

- ui/src/app/shared/components/filter/filter.component.ts
**Issue**: https://github.com/ns1labs/orb/issues/1573
Make filter input listen to enter key event
> fix(orb-ui): #1573 Listen to enter key event in filter input

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
**Issue**: https://github.com/ns1labs/orb/issues/1136
Change wizard engaging text according to type chosen
**Demo**
https://user-images.githubusercontent.com/42921279/181295561-6e451d32-b457-457d-8ae2-fb19c6e036e7.mp4
> feature(orb-ui): #1136 Change wizard engaging text according to type chosen

- ui/src/app/common/services/sinks/sinks.service.ts
- ui/src/app/pages/sinks/delete/sink.delete.component.html
**Issue**: https://github.com/ns1labs/orb/issues/1183
- Apply default style to input from sink removal modal
- Remove cache management from delete sink function to prevent undefined being thrown
https://user-images.githubusercontent.com/42921279/181319149-084fd2fe-665f-4eb2-8af4-830c93b934d9.mp4
> fix(orb-ui): #1183 Implement autosuggestion to all removal modal

- ui/src/app/common/interfaces/orb/filter-option.ts
- ui/src/app/common/services/filter.service.ts
- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.ts
- ui/src/app/pages/fleet/agents/list/agent.list.component.ts
- ui/src/app/pages/fleet/groups/list/agent.group.list.component.ts
- ui/src/app/pages/sinks/list/sink.list.component.ts
- ui/src/app/shared/components/filter/filter.component.html
- ui/src/app/shared/components/filter/filter.component.scss
- ui/src/app/shared/components/filter/filter.component.ts
* make substring match case insensitive
* add exact match/substring match toggle for simple string properties and tag property filters.
> feat(orb-ui): String Search enhancements

- ui/src/app/common/services/orb.service.ts
* fix policy view not rendering when deleting all sinks it indirectly points to
> fix(orb-ui): #1543 fix policy view not rendering when deleting all sinks

- ui/src/app/common/services/agents/agents.service.ts
* fix policy count per agent wrong in agent view
> fix(orb-ui): #1347 count of policies fixed

- ui/src/app/shared/components/filter/filter.component.html
> quickfix(orb-ui): #1535 fix display value when exact match

- python-test/features/agentGroupUi.feature
- python-test/features/steps/control_agent_group_ui.py
- Add a group with a description
> add a group with description

- python-test/README.md
- python-test/features/environment.py
- python-test/features/steps/control_agents_ui.py
- python-test/features/steps/login_ui.py
- python-test/features/steps/ui_utils.py
- python-test/test_config.ini.tpl
- enable end-to-end tests to run in headless mode
> headless ui test

- ui/src/assets/text/strings.ts
* remove link to dataset list page from home/dashboard
> fix(orb-ui): #1106 - remove dataset list from home page

- ui/src/app/pages/datasets/dataset-from/dataset-from.component.ts
*fix attempt to iterate on undefined
> fix(orb-ui): #1586 dataset component error

- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/shared/components/orb/agent/agent-groups/agent-groups.component.html
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.ts
* make agent view groups look like the one in policy view
> feat(orb-ui): #1534 agent view groups card

- ui/package.json
- ui/src/app/auth/auth.token.interceptor.service.ts
* add @auth0/angular-jwt helper library
> fix(orb-ui): redirect to login page when token expires

- cmd/sinker/main.go
- go.mod
- go.sum
- sinker/service.go
- ui/package.json
- ui/src/app/auth/auth.token.interceptor.service.ts
- ui/src/app/pages/datasets/dataset-from/dataset-from.component.ts
- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.html
- ui/src/app/pages/fleet/agents/view/agent.view.component.html
- ui/src/app/shared/components/orb/agent/agent-groups/agent-groups.component.html
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.ts
This PR add changes to production environment
> Add changes to production

- agent/agent.go
- agent/rpc_from.go
Fixes the new panic, and also reset heartbeat routine.
> fix(agent): fix send panic if context is cancelled

- agent/heartbeats.go
- sinker/service.go
Also add another agent fix on heartbeat function
> Fix Sinker Metrics taking too much time to load

- python-test/features/sinkManagementUi.feature
- python-test/features/steps/control_sink_ui.py
- python-test/features/steps/page_objects.py
The UI test to create a new sink item
> Add  a new sink management

- ui/src/app/pages/datasets/dataset-from/dataset-from.component.html
- ui/src/app/pages/datasets/dataset-from/dataset-from.component.ts
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
- ui/src/app/pages/fleet/agents/add/agent.add.component.html
- ui/src/app/pages/fleet/agents/add/agent.add.component.ts
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.html
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.ts
- ui/src/app/pages/sinks/add/sink.add.component.html
- ui/src/app/pages/sinks/add/sink.add.component.ts
- ui/src/app/shared/components/orb/tag-control/tag-control.component.html
Add max length validator to name, description and other text inputs.
> fix(orb-ui): #1602 max length input field

- ui/src/app/pages/fleet/agents/key/agent.key.component.ts
- ui/src/app/shared/components/orb/agent/agent-provisioning/agent-provisioning.component.ts
append --restart=always to docker run command
> feat(orb-ui): #1676 docker command

- python-test/features/steps/ui_utils.py
This PR fixes the integration tests to run on git actions pipeline using command line
> [FIX] ui test for pipeline

- .github/workflows/agent.yml
This PR add repository dispatch to agent build
> [FIX] add repository dispatch

- .github/workflows/go-develop.yml
- .github/workflows/go-main.yml
- .github/workflows/go-production.yml
- agent/docker/orb-agent-entry.sh
This PR add crashpad on agent docker images
> [Feat] add crashpad on agent docker images

- agent/backend/pktvisor/pktvisor.go
- agent/cloud_config/cloud_config.go
- sinker/prometheus/client.go
> feat(agent): fix pktvisor return 2xx status code.

- .github/workflows/agent.yml
- .github/workflows/go-develop.yml
- .github/workflows/go-main.yml
- .github/workflows/go-production.yml
- agent/docker/orb-agent-entry.sh
This PR add crashpad auto initialization on orb agent
> [Feat] Add auto crashpad init

- .github/workflows/agent.yml
- .github/workflows/go-develop.yml
- .github/workflows/go-main.yml
- .github/workflows/go-production.yml
This PR is fixing auto crashpad initialization
> [FIX] Auto crashpad

- .github/workflows/go-production.yml
This PR fixed the override values on buildx agent image
> [FIX] buildx

- .github/workflows/go-production.yml
This PR update folder when we update prod environment on orb-live-manifest repository, to help deploy
> [Feat] update folder when update prod

- agent/rpc_from.go
Fix sometimes failure on marking success if the cancelFunc has not yet set.
> fix(agent): add rpc nil safe.

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.scss
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.ts
- ui/src/app/shared/components/orb/policy/policy-details/policy-details.component.html
- ui/src/app/shared/components/orb/policy/policy-details/policy-details.component.ts
- ui/src/app/shared/components/orb/tag-control/tag-control.component.html
> feat(orb-ui): #1695 add tag input for policies

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
* fix undefined policy handler filters
> fix(orb-ui): #1715-fix-policy-handler-filters

- policies/api/http/endpoint.go
- policies/postgres/policies.go
Add tags to policyList response payload
also, add to addDataset creation parameters to be able to return on datasetList response
> fix(policy/dataset): add tags to response of dataset and policies list endpoints

- agent/docker/orb-agent-entry.sh
This PR extract geodb from geo-db folder and set the trap to monitor SIGINT signal on container entrypoint
> Extract geodb and fix container stop

- .github/workflows/go-production.yml
> [FIX] prod pipeline

- .github/workflows/go-production.yml
> [FIX] prod pipeline (#1770)

- .github/workflows/go-develop.yml
- .github/workflows/go-main.yml
- .github/workflows/go-production.yml
- agent/backend/pktvisor/pktvisor.go
This PR add geo db as default options on agent
> [Feat] add geo db as default options

- agent/docker/Dockerfile
- agent/docker/orb-agent-entry.sh
- agent/docker/run-agent.sh
- fix agent stop with ctrl+c,  exit entrypoint script when received SIGINT
- pass the SIGTERM signals received on container entrypoint to orb agent process stop
> [FIX] agent stop with ctrl+c

- fleet/api/http/openapi.yaml
> doc(fleet): fix operationID of matching agents path

- .github/workflows/agent.yml
- agent/backend/pktvisor/pktvisor.go
This PR fix geo-db parameters on agent.yaml pipeline dispatched by pktvisor repository
> [FIX] agent.yaml geo-db params

- sinks/api/http/endpoint_test.go
- sinks/api/http/transport.go
- sinks/mocks/sinks.go
add missing tag param decode on list sinks endpoint and unit test
> fix(sinks): add tags param to url decode for list sinks endpoint

- .github/workflows/agent.yml
> [FIX] agent.yml pipeline

- agent/backend/cloudprober/cloudprober.go
- agent/backend/cloudprober/cloudprober_test.go
- agent/backend/cloudprober/type.go
- agent/otel/cloudprobereceiver/config_test.go
- agent/otel/cloudprobereceiver/e2e_test.go
- agent/otel/cloudprobereceiver/factory_test.go
- agent/otel/cloudprobereceiver/receiver_test.go
- agent/otel/cloudprobereceiver/setup_test.go
Enabling support for target hostnames
> feat(cloudprober): enable simple policy support to apply

- agent/otel/cloudprobereceiver/e2e_test.go
> Fix test e2e

- agent/otel/cloudprobereceiver/e2e_test.go
> [FIX] e2e test

- agent/policyMgr/manager.go
policy repo was being updated before applying on backend so policy state was set as unknown. This way it will show up correctly on front end
> update policy repo inside agent with policy status after applying on backend

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.scss
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
Add form input for policy backend selection.
> feat(pinger, ui): add form input for policy backend selection

- ui/src/app/shared/components/orb/policy/policy-details/policy-details.component.html
- ui/src/app/shared/components/orb/policy/policy-details/policy-details.component.ts
* fix tag incorrectly displaying policy tags after editing it.
> fix(orb-ui): #1804 fix tag display on policy view

- .github/workflows/go-develop.yml
This PR add automatically update documentation when openapi.yml be changed
> [Feat] add auto update docs

- .github/workflows/agent.yml
> Update golang 1.19

- .github/workflows/go-production.yml
> [FIX] golang version 1.19

- maestro/redis/consumer/streams.go
[FIX] topic name for delete event from sinks
> [FIX] topic name for delete event from sinks

- .github/workflows/go-develop.yml
- .github/workflows/go-production.yml
[Feat] Add maestro microservice on pipeline
> [Feat] Add maestro microservice on pipeline

- .github/workflows/go-develop.yml
- Makefile
- README.md
> [Feat] Add code coverage

- .github/workflows/go-develop.yml
> [FIX] upload report

- .github/workflows/go-develop.yml
This PR add refresh on go report card (https://goreportcard.com/)
> [Feat] add refresh go report card

- agent/docker/agent.yaml
- agent/docker/orb-agent-entry.sh
This PR adds agent short way - #1897
> [Feat] Short way agent privisioning command

- sinker/otel/components.go
- sinker/otel/orbreceiver/otlp.go
> feat(sinker): Fix sinker creation of transform processor

- sinks/api/grpc/client.go
> feat(sinker): Fix encoding filter

- ui/src/app/pages/fleet/agents/view/agent.view.component.ts
Agent Match popup not linking to correct agent FROM agent view
- paramChange not triggering page reload - changed route reuse strategy
> fix(ui): #1795 Matching Agents Redirect

- ui/src/app/pages/fleet/agents/key/agent.key.component.html
- ui/src/app/pages/fleet/agents/key/agent.key.component.ts
- ui/src/app/shared/components/orb/agent/agent-provisioning/agent-provisioning.component.html
- ui/src/app/shared/components/orb/agent/agent-provisioning/agent-provisioning.component.ts
Change suggested interface from 'mock' to 'auto'
> feat(ui): Change 'mock' to 'auto' interface

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.scss
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
Add a backend selector for policies at creation.
> feat(ui): user to select policy backend

- ui/src/app/shared/components/orb/policy/policy-details/policy-details.component.html
Add backend and version informatino to policy view
> feat(ui): Add Policy backend and version information

- maestro/redis/consumer/streams.go
> feat(sinker): fixes panic.

- sinker/otel/kafkafanoutexporter/kafka_exporter.go
This PR fixes the kafka topic to fit with collector config
> [FIX] kafka topic

- sinker/otel/kafkafanoutexporter/kafka_exporter.go
> [FIX] kafka metrics topic

- maestro/config/config_builder.go
> feat(maestro): remove quotes from config.

- agent/docker/orb-agent-entry.sh
> fix removing auto

- sinker/otel/kafkafanoutexporter/kafka_exporter.go
fix log lines on kafka fanout exporter
> [FIX] log lines on kafka fanout exporter

- sinker/otel/bridgeservice/bridge.go
- sinker/otel/orbreceiver/otlp.go
fix logs information on receiver
> [FIX] logs information on receiver

- cmd/agent/main.go
set agent default environment values
> [FIX] set agent default environment values

- sinks/redis/producer/streams.go
- sinks/sinks_service.go
> feat(sinks): fix decrypt metadata to send to redis

- .github/workflows/deploy-stg.yml
Add deploy to stg when necessary
> Dispatch deploy to stg when necessary (#1990) deploy to stg when necessary

- sinker/otel/orbreceiver/otlp.go
> feat(sinker): fix typos in formats

- sinker/otel/orbreceiver/otlp.go
> fix(sinker): remove agent groups and ownerID from metrics.

- sinker/otel/orbreceiver/otlp.go
> fix(agent): fix metric types in switch

- agent/otel/otlpmqttexporter/otlp.go
> fix(agent): fix inject

- cmd/maestro/main.go
- maestro/config/config_builder.go
- maestro/redis/consumer/hashset.go
- maestro/redis/consumer/streams.go
- maestro/service.go
> fix(maestro): fixes hardcoded url

- maestro/config/config_builder.go
- maestro/config/config_builder_test.go
This PR expose healthcheck and pprof endpoints on k8s deployment
> [FIX] expose healthcheck port

- .github/workflows/go-develop.yml
This PR back the test coverage to run only when have changes on orb files
> Run coverage only when have changes on microservices

- sinker/otel/orbreceiver/otlp.go
> feat(sinker): remove job, and fix how to add/remove attributes.

- python-test/README.md
This PR is only to force tests to run again with the new pktvisor image.
> agent with correct pktvisor db

- .github/actions/slack-post/entrypoint.sh
Format changelog message on post message on slack git actions
> Format changelog message on slack

- fleet/comms_types.go
- python-test/features/integration_config_file.feature
- python-test/features/integration_config_file.py.feature
- python-test/features/steps/agent_config_file.py
- python-test/features/steps/control_plane_agents.py
- python-test/features/steps/control_plane_policies.py
- python-test/features/steps/local_agent.py
- python-test/features/steps/taps.py
Add changes on production environment
> Add changes on production environment

- ui/src/app/shared/components/orb/policy/policy-datasets/policy-datasets.component.html
- ui/src/app/shared/components/orb/policy/policy-datasets/policy-datasets.component.ts
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.scss
fix: add buttons to edit/delete dataset.
> fix(ui): Enable Dataset editing and deletion

- python-test/features/integration_config_file.feature
- python-test/features/metrics.feature
- python-test/features/steps/control_plane_agents.py
- python-test/features/steps/control_plane_policies.py
- python-test/features/steps/utils.py
- python-test/test_config.ini.tpl
- validating if policies with each metric groups apply and scrapes successfully
> metric groups test

- ui/src/index.html
workaround for mainflux service appending reset password url + token to referer url
> hotfix(ui): change referrer policy to 'origin'

- kind/Chart.lock
This PR fixes Chart.lock url on kind environment
> [FIX] chart lock url

- maestro/kubecontrol/monitor.go
> feat(maestro): fix message with error in mid-sentence.

- sinker/redis/producer/streams.go
This PR fixes DeployCollector function that was being called however it was unimplemented
> [FIX] DeployCollector function

- maestro/redis/consumer/streams.go
This PR fixes deleteCollector event triggered by sinks micro service to maestro microservice
> Fix delete sinks on maestro

- cmd/migrate/main.go
> feat(migrate): fix migration applying all migrations, only last one is necessary

- maestro/kubecontrol/monitor.go
- pkg/types/maps.go
- sinker/redis/consumer/streams.go
- sinks/sinks_service.go
- sinks/sinks_service_test.go
> fix(sinks): fix merging of the sinks tags and config.

- maestro/kubecontrol/kubecontrol.go
- maestro/redis/consumer/hashset.go
- maestro/service.go
> fix(maestro): fix maestro redis proper client.

- maestro/kubecontrol/kubecontrol.go
- maestro/redis/consumer/hashset.go
- maestro/service.go
- sinker/redis/sinker.go
> fix(maestro): added fine tuning to maestro.

- maestro/monitor/monitor.go
- maestro/redis/consumer/streams.go
- maestro/service.go
> fix(maestro): fix maestro reading events.

- maestro/kubecontrol/kubecontrol.go
- maestro/monitor/monitor.go
- maestro/redis/consumer/streams.go
- maestro/service.go
> fix(maestro): fix maestro reading redis and groups

- maestro/redis/consumer/streams.go
> fix(maestro): re-added maestro stream.

- maestro/monitor/monitor.go
> fix(maestro): fix iteration to be more performatic and less error prone.

- maestro/monitor/monitor.go
> fix(maestro): fix extract id.

- maestro/redis/consumer/streams.go
- sinker/redis/producer/streams.go
- sinks/redis/producer/streams.go
This reverts commit 44f4b98d92e89905015f3e2a0ec9961b8928f977.
> Revert "fix(redis): add debug logs"

- maestro/redis/consumer/streams.go
> fix(maestro): fix acking messages on error.

- README.md
> [ORB-669] - Add more changes on README

- maestro/redis/consumer/streams.go
- sinker/otel/bridgeservice/bridge.go
- sinks/redis/consumer/streams.go
This PR set last activity on redis if sink already is active
>  [FIX] set last activity on redis if sink already is active

- .github/workflows/go-develop.yml
This PR makes run codecov when it is merged on branch
> [feat] Run codecov when is merged on branch

- .github/actions/go-report/Dockerfile
- .github/actions/go-report/action.yml
- .github/actions/go-report/entrypoint.sh
- .github/ci/go-report-comment-template
- .github/workflows/go-develop.yml
- README.md
This PR fixes readme with new github organization and codecov, go-reportcard to comment properly on PR
> [fix] readme, codecov, go-reportcard

- maestro/monitor/monitor.go
- sinker/otel/bridgeservice/bridge.go
This PR makes sink "warning" state be reversible
> [FIX] Making sink warning state as reversible

- sinks/api/http/endpoint.go
- sinks/api/http/endpoint_test.go
- sinks/api/http/openapi.yaml
- sinks/api/http/requests.go
- sinks/api/http/requests_test.go
- sinks/mocks/sinks.go
- sinks/postgres/sinks.go
- sinks/sinks_service.go
- sinks/sinks_service_test.go
Addressed comments on PR Review #2260
> fix(sinks): add unit tests and validate entirely the partial update for sinks

- cmd/sinker/main.go
- sinker/message_handler.go
- sinker/redis/producer/streams.go
> fix(sinker): add logger to eventstore.

- maestro/config/config_builder.go
This PR activate prometheus auto-discovery for otelcollectors provisioned after this change
> add prometheus auto-discovery on otelcollector

- ui/docker/Dockerfile
This PR fix GTAGID on UI dockerfile
> [Fix] GTAGID on dockerfile

- ui/src/app/pages/fleet/agents/key/agent.key.component.ts
- ui/src/app/shared/components/orb/agent/agent-provisioning/agent-provisioning.component.ts
Remove `ORB_OTEL_ENABLE=true` from provisioning command
> feat(orb-ui): #722 remove orb otel enable

- agent/otel/otlpmqttexporter/otlp.go
- sinker/otel/orbreceiver/otlp.go
> Add orb specific data on scope metrics attributes and not on each metric attributes

- sinker/config_state_check.go
- sinker/otel/components.go
- sinker/service.go
> (feat) add otel logs components to kafka

- agent/backend/diode/diode.go
- cmd/agent/main.go
> [fix] condition to run diode

- .github/workflows/agent.yml
> [fix] agent workflow dispatch

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
> [fix] ui on policy add

- sinker/otel/kafkafanoutexporter/factory.go
> fix(sinker): producer payload size

- Makefile
- docker/Dockerfile.debug
Adding make goal to compile orb with delve.
> Adding make goal to compile orb with delve

- maestro/config/config_builder.go
This PR remove k8s limits on otelcollector pod
> [fix] remove k8s limits on otelcollector pod

- sinks/api/http/endpoint.go
- sinks/api/http/endpoint_test.go
- sinks/api/http/requests.go
@manrodrigues another one 
@brnvalenca sorry about that!
> fix(sinks): fix receiveing parameter as json or yaml.

- sinks/api/http/endpoint.go
- sinks/api/http/endpoint_test.go
- sinks/migrate/m1_upgrade_config.go
- sinks/sinks_service.go
- sinks/sinks_service_test.go
- fix bad gateway during partial update, when we dont send config on request
- returning migrate sinks procedure to state of commit **f17d36c**
> fix(sinks): bad gateway during partial update

- .github/labeler.yml
- .github/workflows/labeler.yaml
This PR is adding labels to PRs
> feat(ci): Add labels on pull requests

- sinker/redis/sinker_test.go
> fix(sinker): add test in redis

- .github/dependabot.yml
> feat(ci): add dependabot

- ui/src/app/shared/components/orb/agent/agent-policies-datasets/agent-policies-datasets.component.html
> improvement(orb-ui) Agent View, include policy backend on active policies list

- sinker/otel/bridgeservice/bridge.go
- sinker/otel/orbreceiver/logs.go
- sinker/otel/orbreceiver/metrics.go
- sinker/otel/orbreceiver/traces.go
Labels from local development scraping
> fix(sinker): add ownerID to policy call.

- maestro/monitor/monitor.go
This will enable to find more errors on collectors
> fix(maestro): increase log tail on otel-collectors.

- ui/src/app/shared/components/orb/agent/agent-provisioning/agent-provisioning.component.html
- ui/src/app/shared/components/orb/agent/agent-provisioning/agent-provisioning.component.scss
- ui/src/app/shared/components/orb/agent/agent-provisioning/agent-provisioning.component.ts
> feat(orb-ui): #1106 Agent View, include provisioning command with config file

- maestro/redis/consumer/sinker.go
- maestro/redis/consumer/sinks.go
- maestro/service.go
- maestro/service/deploy_service.go
- maestro/service/metrics_middleware.go
- sinker/otel/orbreceiver/logs.go
- sinker/otel/orbreceiver/metrics.go
- sinker/otel/orbreceiver/traces.go
adding a few logs to handle messages, and add metrics to maestro to track how much messages it is receiveing and processing.
> feat(maestro): add observability and logs to new flow on maestro.

- maestro/deployment/repository.go
> fix (maestro): lastInsertId not necessary

- agent/backend/otel/scrape.go
- agent/backend/otel/vars.go
- agent/backend/pktvisor/scrape.go
- agent/backend/pktvisor/vars.go
- agent/otel/otlpmqttexporter/factory.go
- cmd/agent/main.go
- fix setting default backend variables
- fix scraping metrics from pktvisor over http protocol
- simplify and tidy up code around backends
> fix(agent): pktvisor + otel backends

- python-test/features/integration.feature
we will back it to smoke tests as soon as it is fixed
> eng-1635-temp-mute-remotely-restart-scenario

- python-test/features/agentsProvider.feature
we will back it to smoke tests as soon as it is fixed
> eng-1632-temp-mute-2-agents-same-port

- python-test/features/integration_config_file_pktvisor.feature
A few typos missed in https://github.com/orb-community/orb/pull/2879
> fix: pktvisor backend integration tests

- ui/src/app/auth/pages/login/login.component.scss
- ui/src/app/auth/pages/register/register.component.html
- ui/src/app/auth/pages/register/register.component.scss
> feat(ui): add privacy policy.

- sinks/api/http/endpoint_test.go
- sinks/sinks_service.go
Part 2 of https://github.com/orb-community/orb/pull/2894
Tested locally on k8s with kind.
> fix(sinks): decrypt metadata only if password is encrypted

- cmd/migrate/main.go
> fix(migrate): add all migrations to orb-migrate image. 
