orb-community/orb

- ui/src/environments/environment.defaults.ts
- ui/src/environments/environment.prod.ts
Set up different endpoint urls based on --prod or default builds,
prepending orb defined endpoints url with *<api_url_prefix><version_number>*
eg.: `sinksUrl: '/sinks'` -> `sinksUrl: '/api/v1/sinks'`
closes #86
> feat(angular-prod-env): add api versioning to endpoint urls

- ui/src/app/shared/components/table/table.component.html
remove hover event of c[RUD] button group of each row
* remove `*ngIf="row['isHover']` from button group of each sink row.
Table to be replaced before the weekend anyways, just to make testing easier now
> refactor(orb-ui sinks#table): remove hover event 

- ui/README.md
- ui/src/app/pages/sinks/add/sink.add.component.html
@manrodrigues I've completed the Sink Add Page with basic tag info and also updated the `README.md`.  
I've created a page with examples [](https://github.com/ns1labs/orb/wiki/UI-QA-Automation-Tags), but you can check further additions [here](https://github.com/ns1labs/orb/pull/222/files) :)  
*(This Pull Request is good to be merged, or the branch preserved until all pages have their respective automation tags.)*  
>Add data-orb-qa-id to some elements of `sink.add.component` for testing.
>@manrodrigues besides id for static and dynamic content, such as tables, is there any other type of metadata you could use?
>I've added just a few tags for you to test and give some feedback. There are a few links below for reference. :)
>https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attribute …
> feat(orb-ui orb-tests): Add data-* attr to automated testing

- ui/docker/Dockerfile
Update [Dockerfile](./ui/docker/Dockerfile) to use yarn instead of npm.
Yarn resolves peer deps and package conflicts with more ease.
Also quicker than update the giant package.json dep list RN.
Update Orb UI dockerfile commands
> feat(orb-ui orb-docker): Dockerfile update npm to yarn

- ui/src/app/pages/fleet/groups/add/agent.group.add.component.ts
Agent Group Create and Update pages routing to blank page.
Fix AgentGroup Create & Update pages redirect to blank page, either canceling or completing the process.
Closes #220
> fix(orb-ui orb-agents): #220 fix agentGroup redirect 

- ui/src/environments/environment.defaults.ts
Soon to be removed environment.prod.beta.ts GTMID property was being
overwritten by environment.ts late definition of GTMID.
Soon to be replaced with GTMID injection via node env.
> fix(orb-ui orb-beta): fix bad overwritte in GTAG

- ui/src/app/pages/fleet/agents/add/agent.add.component.ts
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.ts
- ui/src/app/pages/sinks/add/sink.add.component.ts
Add name input validators for `name` fields of `Agent`, `AgentGroup` and `Sink` Orb entities.
> fix(orb-ui): formControl name input validators

- ui/src/app/pages/pages-menu.ts
disable any unfinished pages from showing via menu
> fix(orb-ui): disable datasets link in pages-menu

- docker/.env
change `MF_RELEASE_TAG=latest` to `MF_RELEASE_TAG=0.12.1`
fix orb system not booting up correctly
> fix(orb-dockers): change mainflux version for docker builds

- ui/src/app/pages/fleet/agents/key/agent.key.component.html
- ui/src/app/pages/fleet/agents/key/agent.key.component.ts
Closes #380 
@manrodrigues Instead of showing a message, the icon is changed after clicking and copy.
> fix: #380 change copy icon after click

- ui/src/app/pages/sinks/add/sink.add.component.html
- ui/src/app/pages/sinks/details/sink.details.component.html
Remove red asterisk marking key/value pair and tag fields of sink as required.
#621
> fix(orb-ui): #621 sink tags not required

- policies/api/http/endpoint_test.go
- policies/api/http/transport.go
Change the http verb on dataset edition
Using put and not patch to keep the project consistence
> fix(dataset): Fix http patch to put on edition.

- ui/src/app/pages/fleet/agents/add/agent.add.component.html
- ui/src/app/pages/fleet/agents/list/agent.list.component.html
- ui/src/app/pages/sinks/add/sink.add.component.html
* Show message in agent add and agent list page warning user that agent has no tags to it.
* Also fix string for tag color on sink page
> feat(orb-ui): #640 display warning when no tags added for agent

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
fix(orb-ui): add missing asterisk to handler label field
> fix(orb-ui): #368 all required fields should have asterisk

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
Add 'e.g.: ' to placeholder information texts
> fix(orb-ui): add 'e.g.: ' to examples

- policies/postgres/init.go
Set valid value for postgres 'schema_version' column on script for migration
> Fix policies migrations error

- python-test/features/steps/users.py
The account must only be registered once, so after registration the variable that indicates whether the account is registered or not  (`is_credentials_registered`) must be changed
> changing is_credentials_registered variable after register the account

- python-test/features/steps/control_agents_ui.py
- python-test/features/steps/login_ui.py
- The missing quotes were resulting in the wrong agents being parsed when the orb had more than one agent.
- The change made to the authentication function had not yet been applied to the UI tests
> get correct agent through UI

- sinker/backend/pktvisor/pktvisor.go
- sinker/backend/pktvisor/pktvisor_test.go
Revert sinker to send metrics even when it's 0
> Avoiding NaN on prometheus

- ui/package.json
set `@types/node` version to 12.20.42.
12.20.43 breaks dependency compat.
> (hotfix): @types/node version set to 12.20.42

- ui/src/app/pages/register/register.component.html
* require two names, space separated, for full user name
* send full user name as signer id when contract agreement
* pactsafe confirmation email set to true - user should receive a copy of contract
> fix(orb-ui): #96 pactsafe parameters

- ui/src/app/pages/datasets/policies.agent/add/handler.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/handler.policy.add.component.scss
* fix issue #865 button order is wrong in handler modal
> fix(orb-ui): fix handler modal button positions

- policies/api/http/responses.go
Today, if a policy is created, the version number is empty until editing the policy. By this change, it will start at zero right after creating
> fix(policy): set version number to display zero after creating

- ui/src/app/shared/components/orb/agent/provisioning/agent-provisioning.component.html
move click event listener to button container, parent of icon which was currently listening on click event
> fix(orb-ui): move click event listener to button container

- ui/src/app/pages/datasets/dataset-from/dataset-from.component.html
- ui/src/app/shared/components/orb/policy/policy-datasets/policy-datasets.component.ts
* name field should be last in form
* policy selector should not appear when creating dataset from policy view.
* group selector should not appear when creating dataset from agent group view(does not exist as of yet)
> feat(orb-ui): few changes to dataset modal

- ui/src/app/pages/pages-menu.ts
- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.html
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.ts
Fix wrong text for policy without groups linked, move agents and groups outside of fleet and name key values pair as tag on agents view to maintain the pattern of Orb
> wrong text for policies, menu without children, key value as tags

- ui/src/app/pages/fleet/groups/list/agent.group.list.component.ts
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.html
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.scss
- ui/src/app/shared/components/orb/policy/policy-groups/policy-groups.component.ts
- ui/src/app/shared/shared.module.ts
* add tooltip displaying online and total agents for group when hovering group name
* open matching agents list dialog when clicking on agent group name
* shows number of online agents in parenthesis - i.e.: 'agent_group_name(3)' for 3 online agents
* change card title to 'Assigned Groups'
latest UI on Figma I believe
> feat(orb-ui): #1105 show matching agents for agent group in policy view

- ui/src/app/pages/datasets/dataset-from/dataset-from.component.html
rollback dataset-from rule for showing agent_group_id selector dropdown.
> fix(orb-ui): rollback dataset-from rule for showing agent_group_id

- policies/policy_service.go
quicky fixes:
- fix error response of duplicate policy endpoint
- fix the logic of automatic generate name of copy
> fix(policy): fix duplicate policy http error response

- ui/src/app/pages/datasets/dataset-from/dataset-from.component.scss
- ui/src/app/shared/components/orb/sink-control/sink-control.component.html
- ui/src/app/shared/components/orb/sink-control/sink-control.component.scss
* fix selector size
* fix disable selector when no available sink to choose from
> fix(orb-ui): #1217 sink selector size

- ui/src/app/shared/components/orb/combined-tag/combined-tag.component.html
- ui/src/app/shared/components/orb/combined-tag/combined-tag.component.ts
https://github.com/ns1labs/orb/issues/1242#issuecomment-1140059666
add tooltip to agent and orb tags, remove unified|split thing button
> fix(orb-ui): add tooltips to agent and orb tags display

- agent/agent.go
- agent/backend/pktvisor/pktvisor.go
- agent/comms.go
- agent/rpc_from.go
This fixes #1120 
This adds the restart comms in the agent reset, and it managed to remotely fix any connection issues of desynchronization of subscription / unsubscription with the agent.
logs
```
{"level":"info","caller":"agent/agent.go:198","msg":"restarting all backends","reason":"Reset initiated from control plane"}{"level":"info","caller":"agent/agent.go:200","msg":"restarting backend","backend":"pktvisor","reason":"Reset initiated from control plane"}
{"level":"info","caller":"agent/agent.go:159","msg":"restarting backend","backend":"pktvisor","reason":"Reset initiated from control plane"}
{"level":"info","caller":"agent/agent.go:160","msg":"removing policies","backend":"pktvisor"}
{"level":"info","caller":"pktvisor/pktvisor.go:258","msg":"pktvisor stdout","log":"[2022-06-06 …
```
> fix(agent): add reset comms method and extract call

- agent/comms.go
This relates to the issue #1334
> fix(agent): remove the ConnectRetry behavior from paho client.

- Makefile
- agent/comms.go
- fleet/comms.go
- fleet/postgres/agents.go
- go.mod
- go.sum
- python-test/features/integration.feature
Removes the state update when the Agent communicates the capabilities to Fleet. 
agent.State should only change in the Heartbeat flow
> fix(agent/fleet): Remove the state update on the handleCapabilities flow

- agent/backend/pktvisor/pktvisor.go
Created a simple verification when starting up the pktvisor backend to await for it to be ready before starting the orb client.
fixes #1419
> Added readiness for pktvisor backend

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.scss
> fix(orb-ui): #1406 - Align add handler button to the left

- ui/src/app/pages/fleet/agents/add/agent.add.component.html
- ui/src/app/pages/fleet/agents/add/agent.add.component.scss
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.html
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.scss
issue #1407
There were some col-8 properties that seemed to reduce the size of the elements with no need, only to make the component readable on small device. However, changing the min-width property to be only width should solve this problem and we have the following behavior:
https://user-images.githubusercontent.com/101733592/177414396-365dc20c-d8d9-439d-8335-594b65338965.mp4
> fix(orb-ui): #1106 - Fix add components sizes

- policies/api/http/endpoint.go
- ui/src/app/common/services/agents/agent.policies.service.ts
- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.ts
issue #1018
Besides the issue with the yaml error message when trying to create the policy, the page was going to the next step even with errors:
https://user-images.githubusercontent.com/101733592/177845417-bb3bdf71-50fb-4cbc-864c-4d6462cb9dfb.mp4
After fix, a more detailed error message is shown, and we stay at the current step:
The error messages shown when trying to edit the policies where also improved. The error with JSON was not even verified before:
> fix(orb-ui): #1018 - Improve policy error msgs

- agent/backend/pktvisor/pktvisor.go
- agent/comms.go
Integration Test report running against Staging
Logs of the reconnection attempts while offline
```logs
2022-07-08T15:13:55.746Z	ERROR	agent/logging.go:43	CRITICAL mqtt log	{"payload": ["[pinger]  ","pingresp not received, disconnecting"]}
github.com/ns1labs/orb/agent.(*agentLoggerCritical).Println
/go/src/github.com/ns1labs/orb/agent/logging.go:43
github.com/eclipse/paho%2emqtt%2egolang.keepalive
/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.4.1/ping.go:72
2022-07-08T15:13:55.746Z	DEBUG	agent/logging.go:37	DEBUG mqtt log	{"payload": ["[client]  ","internalConnLost called"]}
2022-07-08T15:13:55.746Z	DEBUG	agent/logging.go:37	DEBUG mqtt log	{"payload": ["[client]  ","stopCommsWorkers called"]}
2022-07-08T15:13:55.746Z	DEBUG	agent/logging.go:37	DEBUG mqtt log	{"payload": ["[net] …
```
> feat(agent): successfully on lost connection restore all subs and policies.

- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.html
**Issue:** https://github.com/ns1labs/orb/issues/1457
Enabled reset button only when agent is online or stale
Demo:
> fix(orb-ui): #1457 Enable reset button only when agent is online or stale

- policies/postgres/policies.go
- policies/redis/producer/streams.go
Agent is not applying policy changes after editing because fleet service is failing to handle policy RPC messages for updating policy because of a malformed issue. Policy object that is being used to fill in RPC message does not contain OwnerID, we are only able to get it after the service layer, so we must use the policy object after editing
Also a minor fix to return 409 error code in case of name conflict for editing policy:
> Hotfix/orb 1455 - apply edited policy and 1421 -  Name conflict error in editing policy returns 500 instead of 409

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.html
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.scss
**Issue:** https://github.com/ns1labs/orb/issues/1015
In this PR I've made some small adjustements to make advanced options button look clickable. I thought it was a better idea to create a new class so I wouldn't risk to override another nb-accordion-header across the portal.
https://user-images.githubusercontent.com/42921279/179307179-0302f752-b1ec-4b40-a0f1-064cbb3418ed.mp4
> fix(orb-ui): #1015 Make advanced options button look clickable

- ui/src/app/shared/components/poll-control/poll-control.component.html
- ui/src/app/shared/components/poll-control/poll-control.component.scss
- ui/src/app/shared/components/poll-control/poll-control.component.ts
**Issue**: https://github.com/ns1labs/orb/issues/1471
I have fixed the active/focus effect, styled it a little bit and also added an animation while it is fetching the data.
**Before:**
**Now:**
https://user-images.githubusercontent.com/42921279/179325184-91c5582f-5a0f-4336-99ec-d7b45cacd865.mp4
> fix(orb-ui): #1471 Remove selection from reload button once clicked and make it rotate while fetching data

- ui/src/app/shared/components/orb/agent/agent-policies-datasets/agent-policies-datasets.component.ts
**Issue:** https://github.com/ns1labs/orb/issues/1470
Fixed behaviour where dataset modal would not close on click outside
**Before:**
**Now:**
https://user-images.githubusercontent.com/42921279/179526645-9d489c56-078e-4a2e-96fc-eebadabb8c95.mp4
> fix(orb-ui): #1470 Dismiss dataset modal when clicking outside it

- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.scss
**Issue:** https://github.com/ns1labs/orb/issues/1502
Align policy names at the left of table row
**Demo:**
> fix(orb-ui): #1502 Align policy names at the left of table row

- agent/comms.go
- agent/rpc_from.go
A few runs showed that we handled correctly the MQTT EOF failure.
Timeout for connection of 5 minutes.
Shut down the agent if connection doesn't subscribe to control plane.
```
'{"level":"info","ts":1658178237.4211695,"caller":"cloud_config/cloud_config.go:173","msg":"using explicitly specified cloud configuration","address":"tls://stg.orb.live:8883","id":"6d60d1e7-088a-4a3e-9e90-33eeeaff694e"}',
'{"level":"error","ts":1658178238.4985926,"caller":"agent/logging.go:49","msg":"ERROR mqtt log","payload":["[client] ","Connect comms goroutine - error triggered",{}]}', '{"level":"error","ts":1658178238.4987323,"caller":"agent/comms.go:29","msg":"connection to mqtt lost","#attempt":0,"error":"EOF"}', '{"level":"error","ts":1658178238.4987314,"caller":"agent/heartbeats.go:96","msg":"error sending …
```
> feat(agent): remove restart comms indefinetely

- ui/src/app/common/services/agents/agent.policies.service.ts
- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
**Issue:** https://github.com/ns1labs/orb/issues/1500
When trying to create a policy which name was already used before, the user was being redirected to a broken policy view page.
I've mapped the service exception that is thrown from Agent Policy component and also removed the notifications from service to component.
**Before:**
**After:**
https://user-images.githubusercontent.com/42921279/179792086-5e4fa147-79e6-4a4c-b095-94a9fbd9909b.mp4
> fix(orb-ui): #1500 Handle exception thrown when failing to create or edit a new policy

- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.html
- ui/src/app/shared/components/orb/agent/agent-information/agent-information.component.ts
**Issue**: https://github.com/ns1labs/orb/issues/1478
- All empty fields now have a consistent pattern and are filled with a "-"
- Labels renamed to "Agent version" and "Backend version"
> feature(orb-ui): #1478 Improve agent and backend version label and pattern

- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.html
- ui/src/app/pages/datasets/policies.agent/list/agent.policy.list.component.ts
**Issue**: https://github.com/ns1labs/orb/issues/1521
Create button like view|edit|delete to duplicate policy, redirect user to the new policy created and leave a notification whether this process was completed successfully or not.
https://user-images.githubusercontent.com/42921279/180074010-c26b11c4-1399-44f7-ae20-f38ced9ca92b.mp4
> feat(orb-ui): #1521 Allow users to duplicate policies in Policy Management page

- cmd/agent/main.go
- cmd/fleet/main.go
- cmd/migrate/main.go
- cmd/policies/main.go
- cmd/sinker/main.go
- cmd/sinks/main.go
This fixes ns1labs/orb#1463
Logs now
Fleet
```
{"level":"info","ts":"2022-07-21T17:18:40.514Z","caller":"fleet/main.go:289","msg":"Dialed to gRPC service auth at kind-orb-envoy:8181, TLS? false"}
{"level":"info","ts":"2022-07-21T17:18:40.514Z","caller":"fleet/main.go:289","msg":"Dialed to gRPC service policies at kind-orb-envoy:8282, TLS? false"}
{"level":"info","ts":"2022-07-21T17:18:40.516Z","caller":"fleet/comms.go:745","msg":"subscribed to agent channels"}
{"level":"info","ts":"2022-07-21T17:18:40.516Z","caller":"fleet/main.go:302","msg":"Fleet service started using http on port 8203"}
{"level":"info","ts":"2022-07-21T17:18:40.516Z","caller":"fleet/main.go:333","msg":"gRPC service started using http on port 8283"}
{"level":"info","ts":"2022-07-21T17:18:40.516Z","caller":"fleet/agent_st …
```
> fix(services): fix ts encoding as iso

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
**Issue**: https://github.com/ns1labs/orb/issues/1547
If a DHCP or NET handler is set, it is created with an undefined filter. My commit ensures to check if is not undefined before checking its length for DNS. 
https://user-images.githubusercontent.com/42921279/180787451-41c273a3-100c-423d-a717-bf75aea4dff8.mp4
> feature(orb-ui): #1547 Only add filter property if it is not empty and if it is valid

- ui/src/app/pages/fleet/groups/add/agent.group.add.component.html
- ui/src/app/pages/fleet/groups/add/agent.group.add.component.scss
**Issue**: https://github.com/ns1labs/orb/issues/1550
Display agent group name and description in column direction and set a limit to text container
**Before:**
**Now:**
> fix(orb-ui): #1550 Display agent group name and description in column direction and set a limit to text container

- ui/src/app/pages/datasets/dataset-from/dataset-from.component.html
- ui/src/app/pages/datasets/dataset-from/dataset-from.component.scss
- ui/src/app/pages/datasets/dataset-from/dataset-from.component.ts
**Issue**: https://github.com/ns1labs/orb/issues/1122
Display a message to user when no agent groups or sinks are available
**Before**
**Now**
> fix(orb-ui): #1122 Display a message to user when no agent groups or sinks are available

- agent/agent.go
- agent/backend/backend.go
- agent/backend/pktvisor/pktvisor.go
- agent/comms.go
- agent/heartbeats.go
- agent/rpc_from.go
- cmd/agent/main.go
- Added context to all go routines to trace and terminate all of them in a cascade.
- Removed fatal log.
- Added validation in stop method if client is still connected, unsub, heartbeat offline and disconnect. If client is not connected, skips.
This fixes #1619
> Agent fix graceful stop and remove fatal

- docker/configs/prometheus.yml
This PR resolve this task:
https://app.zenhub.com/workspaces/orb--pktvisor-board-61a78386a3b924000fb03cbb/issues/ns1labs/orb/565
> [FIX] Add sinker to the list of scraped prometheus metrics in docker-compose config

- agent/agent.go
> fix(agent): unsub from all group channels before restarting comms.

- cmd/sinker/main.go
- fleet/comms.go
- python-test/features/steps/control_plane_policies.py
- sinker/service.go
Enable consume messages asynchronously in fleet and add context cancellation in services that consumes messages.
> Enable Consume Messages async in Fleet

- ui/src/app/pages/datasets/policies.agent/add/agent.policy.add.component.ts
Fix Agent Policy creation through wizard
* unable to read from undefined form when input configuration already predefined.
> fix(orb-ui): fix unable to save policy

- ui/src/app/shared/components/orb/tag-control/tag-control.component.html
- ui/src/app/shared/directives/empty-input.directive.ts
- ui/src/app/shared/shared.module.ts
* add validator to tag key input, invalidating the 'add' tag button when tag key is empty or blank spaces.
> fix(orb-ui): #405 fix tag input 

- agent/agent.go
- agent/backend/backend.go
- agent/backend/pktvisor/pktvisor.go
- agent/backend/pktvisor/policy.go
- agent/backend/pktvisor/scrape.go
- agent/backend/pktvisor/utils.go
- agent/comms.go
- agent/heartbeats.go
- agent/policies/types.go
- agent/policyMgr/manager.go
- fleet/comms_types.go
general improvements to orb-agent's handling of failures in the backend
* split large pktvisor.go into smaller package files
* add new "backend state" for tracking backend restarts
* add more status on backend and policy state to heartbeats
* don't error out when orb-agent fails to remove a policy from a backend; continue removing from the PolicyManager repo
* when checking if pktvisor is alive, check both process status AND REST API accessibility
* if backend is not running, update status for all policies on that backend to Unknown
> orb-agent improvements on backend error

- agent/otel/otlpmqttexporter/otlp.go
- sinker/otel/orbreceiver/otlp.go
Using OTLP the mqtt payload is bigger than regular way by some reason.
So this PR changes:
- compressed otlpmqtt payload with "BestCompression" using brotli algorithm, reducing it size in ~8x:
Metrics still arriving fine after some hours, no mqtt disconnects anymore:
> [Feat] Compress otlp payload with brotli algorithm

- agent/comms.go
- Set to reconnect on OTEL agent when connection broke, on ConnectionLostHandler
> [FIX] set to reconnect on OTEL agent

- agent/docker/orb-agent-entry.sh
This PR fixes agent short form:
Command used to test:
`docker run -d --restart=always --net=host -v /home/user/Downloads/:/usr/local/orb/ -e ORB_CLOUD_MQTT_ID=6e72a741-f148-4c6d-ab47-18296ad3055d -e ORB_CLOUD_MQTT_CHANNEL_ID=6e72a741-f148-4c6d-ab47-18296ad3055d -e ORB_CLOUD_MQTT_KEY=6e72a741-f148-4c6d-ab47-18296ad3055d ns1labs/orb-agent:0.21.0-f8977f7c run -c /usr/local/orb/agent.yaml`
> [FIX] agent short form

- agent/backend/pktvisor/pktvisor.go
- agent/otel/otlpmqttexporter/otlp.go
- sinker/otel/orbreceiver/otlp.go
This PR fixes 
- Otel sinker component panic when we are extracting attribute from metricsRequest object
- Sort datasetIDs before inject on metrics attributes on agent side
- OpenTelemetry log message, that was showing when otel was disabled
> [FIX] otel sinker panic

- sinker/otel/orbreceiver/otlp.go
This PR removes datasetIDs from metricsRequest (otel) attributes, to be sent to prometheus without dataset_ids attribute on metrics
Metrics attributes before change:
Metrics attributes after change:
> [FIX] Remove datasetIDs from metricsRequest object

- agent/docker/orb-agent-entry.sh
This PR remove the default_pcap tap when agent start with config file mounted
> [FIX] agent message about default_pcap

- sinks/sinks_service.go
- sinks/sinks_service_test.go
Remove the need always to send all attributes when updating a sink
Current sink:
Editing only sink name:
Editing only description:
Editing only tags:
> fix(sinks): quick fix sinks api

- python-test/features/integration_config_file.feature
- python-test/features/steps/control_plane_agents.py
- Changing the mqtt address to use agents.orb.live
- Adding tests to validate default pktvisor configs in agents without auto provisioning
> using agents.orb.live as mqtt address

- fleet/comms_types.go
Remove omitempty on PolicyStateInfo struct so the version shows up even when it is 0
> fleet(fix): remove omitempty of version field on PolicyStateInfo struct

- agent/docker/orb-agent-entry.sh
- cmd/agent/main.go
This PR makes agents.orb.live the default mqtt route and the new mqtt routes in the form `tls://agents.${ORB_CLOUD_ADDRESS}:8883`
> agents.orb.live as mqtt's default route

- fleet/postgres/agent_groups.go
- fleet/postgres/agent_groups_test.go
- sinks/postgres/sinks.go
- sinks/postgres/sinks_test.go
add a wrap for errors caused by name conflict on editing so that the status code will be 409 instead of 500
> fix: fix error status code from 500 to 409 for updating agent group or sink with a name conflict

- ui/src/app/pages/datasets/policies.agent/view/agent.policy.view.component.ts
Agent Policy duplication does not redirect to newly created policy.
> fix(ui): #1544 Agent Policy Duplicate Redirect

- sinks/api/http/endpoint.go
- sinks/api/http/requests.go
- sinks/sinks_service.go
- sinks/sinks_service_test.go
following up https://github.com/ns1labs/orb/issues/1985#issuecomment-1355540797
remove the mandatory sink name on the payload for all editing requests unless you want to modify it
and roll back the last update on sink tags management to follow restful guidelines
> remove mandatory sink name on editing endpoint

- sinks/api/http/endpoint_test.go
- sinks/api/http/requests.go
Make sink config mandatory on sink creation and check if it has the minimum amount of keys to create
*Plus make some unit tests more readable
> make config field mandatory on sinks creation

- fleet/agent_group_service.go
- fleet/agent_group_service_test.go
- fleet/agent_groups.go
- fleet/api/http/endpoint.go
- fleet/api/http/endpoint_test.go
- fleet/api/http/requests.go
- fleet/comms_test.go
- fleet/postgres/agent_groups.go
- fleet/postgres/agent_groups_test.go
- policies/api/http/endpoint.go
- policies/api/http/endpoint_test.go
- policies/api/http/requests.go
- policies/mocks/policies.go
- policies/policies.go
- policies/policy_service.go
- policies/policy_service_test.go
- policies/postgres/policies.go
- sinks/api/grpc/endpoint.go
- sinks/api/http/endpoint.go
- sinks/api/http/endpoint_test.go
- sinks/api/http/requests.go
- sinks/postgres/sinks.go
- sinks/postgres/sinks_test.go
- sinks/sinks.go
- sinks/sinks_service.go
- sinks/sinks_service_test.go
- Make it possible to edit tags without any other field being informed in the body, following #2099
- Description:
- If the description field is omitted, nothing changes
- If the description field is informed and empty, The description becomes empty (is removed)
- If the description field is informed and NOT empty, the new description must overwrite the old one
- Fix and add some unit tests
> [ORB-223] Fix/partial updates policies

- fleet/comms_test.go
- policies/api/grpc/endpoint.go
- policies/api/http/endpoint.go
- policies/api/http/endpoint_test.go
- policies/api/http/requests.go
- policies/mocks/policies.go
- policies/policies.go
- policies/policy_service.go
- policies/policy_service_test.go
- policies/postgres/datasets_test.go
- policies/postgres/policies.go
- policies/postgres/policies_test.go
- policies/redis/consumer/streams.go
- policies/redis/producer/streams.go
Support updates on datasets API to name and sinks ids without requiring the other fields to be provided in the JSON body:
Both cases follow the rules:
- If it is informed, the new one must overwrite the old one
- If it is omitted, the old one must be maintained.
- If it is informed with empty or invalid values, an error must be raised informing that the attribute doesn't match the pattern required.
> [ORB-224] partial updates for datasets

- agent/policies/types.go
- agent/policyMgr/manager.go
Add a new policy state when a policy isn't applied because tap selector doesn't match any available taps
> [ORB-170] add 'noTapMatch' state for policies on agent

- agent/policies/types.go
- fleet/agent_group_service.go
- fleet/agent_group_service_test.go
- fleet/agent_groups.go
- fleet/agent_service.go
- fleet/agent_service_test.go
- fleet/agents.go
- fleet/api/grpc/endpoint.go
- fleet/api/http/endpoint.go
- fleet/api/http/endpoint_test.go
- fleet/api/http/requests.go
- fleet/comms_test.go
- fleet/postgres/agent_groups.go
- fleet/postgres/agent_groups_test.go
- fleet/postgres/agents.go
- fleet/postgres/agents_test.go
- policies/postgres/policies.go
- sinker/message_handler.go
Make it unable to delete group tags on the editing process, and fix unit tests
> fix(fleet): fix group tags editing - make it unable to delete tags

- maestro/config/config_builder.go
- maestro/config/config_builder_test.go
This PR deactivate loggin extension on otel collector to reduce unecessary verbose on logs
> Removing logging extension on otel collector

- sinks/api/grpc/client.go
This PR fixes the null parameter OwnerID that is returning on maestro when client.go is used to retrieveSinks from sinks micro service
> [FIX] adding ownerID on decode GRPC sinks response

- cmd/maestro/main.go
- maestro/kubecontrol/kubecontrol.go
- maestro/kubecontrol/monitor.go
- maestro/service.go
- sinker/config/repo.go
- sinker/config_state_check.go
- sinker/otel/bridgeservice/bridge.go
- sinker/redis/producer/streams.go
- sinker/redis/sinker.go
- Added logic to change LastRemoteWrite parameter for active sinks when receive a metric on sinker
- Symplify AnalyzeLogs function to check only errors in otel collector logs
- Removed LastRemoteWrite change on maestro monitorSinks function
- Just change sink status on maestro if it is active
- Fix deployment status on maestro micro service, should be internally controlled and not checking k8s deployment state, cuz can generate wrong status during update sink operation
- Remove otel idle state control from otel-sinker microservice, and added it on maestro with different manner
> [FIX] on logic for active and error sinks status

- maestro/redis/consumer/streams.go
This fixes maestro update otel collector when sink has been updated.
> [FIX] maestro event sourcing to update otel collector

- agent/backend/pktvisor/scrape.go
- agent/otel/bridgeservice.go
- agent/otel/otlpmqttexporter/otlp.go
- maestro/service.go
> feat(agent): fix context propagation for failure in otel

- python-test/features/integration.feature
Those tests must pass locally using OTEL config on test_config. 
behavex -t @sink_status_error --parallel-processes=20 --parallel-scheme=scenario
> inserting tag on test scenarios with error status on sink

- cmd/agent/main.go
This PR set the default path for orb-agent.db to /opt/orb/
> [ORB-673] Set default path for orb-agent.db

- ui/scripts/setenv.ts
- ui/src/environments/environment.prod.beta.ts
- ui/src/environments/environment.prod.ts
Changed https://github.com/orb-community/orb/blob/develop/ui/scripts/setenv.ts to read GTAGID value from environment and write it to https://github.com/orb-community/orb/blob/develop/ui/src/environments/environment.env.ts upon build.
[] requires GTAGID to be defined on build environment
> fix(build:ui): read GTAG from environment variable

- maestro/redis/consumer/hashset.go
- sinker/redis/producer/streams.go
- sinker/redis/sinker.go
- add Redis **MAXLEN** command on every **XADD** to avoid redis be out of memory
> [FIX] Add MaxLen to avoid redis be filled

- python-test/features/steps/mocked_interface.py
Due the problem with integration tests running on pipeline have better behavior using **ip link set dev** instead **ifconfig** to set mto for dummy interface
> Change command to set mtu

- python-test/features/integration.feature
- python-test/features/integration_config_file.feature
i'm removing sink status check of scenarios with flow without metrics.. sanity tests are now running on pipeline and we have validations with metrics there
> removing sink status check of flow without metrics

- maestro/config/exporter_builder.go
- maestro/config/types.go
- sinker/config/types.go
- sinker/config_state_check.go
- sinker/message_handler.go
- sinker/redis/consumer/streams.go
- sinker/redis/sinker_test.go
- sinks/backend/otlphttpexporter/configuration.go
- sinks/backend/prometheus/configuration.go
- sinks/sinks_service.go
Fixed Custom Headers 
Deployment with config yaml
```
receivers:
kafka:
brokers:
- kind-orb-kafka.orb.svc.cluster.local:9092
topic: otlp_metrics-b382f72e-14da-4284-9bad-627136c61e2b
protocol_version: 2.0.0
extensions:
pprof:
endpoint: 0.0.0.0:1888
basicauth/exporter:
client_auth:
username: username
password:password 
exporters:
prometheusremotewrite:
endpoint: https://localhost
headers:
X-Tenant: MY_TENANT_1
auth:
authenticator: basicauth/exporter
service:
extensions:
- pprof
- basicauth/exporter
pipelines:
metrics:
receivers:
- kafka
exporters:
- prometheusremotewrite
```
> fix(sinks): overall sinks fixes with custom headers and a few sanity tests fixes

- maestro/deployment/service.go
- maestro/kubecontrol/kubecontrol.go
- maestro/redis/consumer/sinker.go
- maestro/service.go
- maestro/service/deploy_service.go
- fixed updatedeployment function, was always getting old configuration
- fixed killotelcollector was only deleting deployment, not configmap and service
- fixed sinker activity stream subscribe and event consuption
- fixed sinker idle stream subscribe and event consuption
- fixed delete otel collector when sinks be idle
> fix (maestro): activity and error event synchronization

- python-test/requirements.txt
Fix python-tests, `mkdocs-material` 9.4.7 depends on `mkdocs` 1.5.3
> fix: python-tests - mkdocs-material 9.4.7 depends on mkdocs 1.5.3

- python-test/README.md
- python-test/features/integration_config_file_otel.feature
- python-test/features/integration_config_file_pktvisor.feature
- python-test/features/steps/agent_groups.py
- python-test/features/steps/agents.py
- python-test/features/steps/configs.py
- python-test/features/steps/local_agent.py
- python-test/features/steps/policies.py
- python-test/features/steps/sink.py
tests are added with tag @smoke_otel_backend
set not default variables in test_config.ini:
```
backend_type=otlphttp
agent_docker_image=orbcommunity/orb-agent-full
agent_docker_tag=develop
otlp_publisher_username=12345678
otlp_publisher_key=<pass>
otlp_publisher_endpoint=https://otlp-gateway-prod-us-central-0.grafana.net/otlp
```
> Eng 1512 otel integration tests

- python-test/features/integration_config_file_otel.feature
- python-test/features/integration_config_file_pktvisor.feature
- python-test/features/steps/agent_config_file.py
- python-test/features/steps/agents.py
Fixing integration tests for otel backend (also muted 3 tests as having same issues as for pktvisor from the past) + one typo.
> fix: otel backend integration tests

- sinks/mocks/sinks.go
- sinks/sinks_service.go
- sinks/sinks_service_test.go
We discovered an issue in the sinks service when user updates existing sink (i.e. name, description, tags) without config. In such scenario, encrypted password of the existing config metadata is being encrypted again. This leads to existing sink/otelcollectors not being able to authenticate with prometheus/otlphttp backends. 
For sinks already affected by this issue, the recommended solution is to update existing sinks with correct backend credentials.
> fix(sinks): prevent circular config metadata encryption

- go.mod
- go.sum
`github.com/docker/cli v25.0.1+incompatible` needs compatibility with `github.com/docker/docker v25.0.1+incompatible`
> fix: docker dependency

- agent/heartbeats.go
- python-test/features/steps/agents.py
this adds 30s to timeout on status of orb agent in integration tests.
> fix(agent): add more timeout for python_test

- .github/actions/go-lint/Dockerfile
- .github/actions/go-report/Dockerfile
- .github/workflows/agent.yml
- .github/workflows/go-develop.yml
- .github/workflows/go-main.yml
- .github/workflows/go-production.yml
- agent/docker/Dockerfile
- docker/Dockerfile
- docker/Dockerfile.debug
- fleet/api/http/transport.go
- go.mod
- maestro/kubecontrol/kubecontrol.go
- maestro/postgres/init.go
- maestro/redis/consumer/sinker.go
- pkg/errors/types.go
- sinker/redis/consumer/sink_key_expire.go
- sinks/api/http/requests.go
- sinks/api/http/transport.go
- sinks/authentication_type/basicauth/authentication.go
Change mainly due to goreport requiring go1.22 and blocking PRs, but this upgrade been long overdue anyway.
> chore: upgrade to go 1.22

- maestro/config/authentication_builder.go
- maestro/config/config_builder_test.go
- maestro/config/types.go
- pkg/errors/types.go
- sinks/api/http/endpoint_test.go
- sinks/api/http/requests.go
- sinks/api/http/transport.go
- sinks/authentication_type/basicauth/authentication.go
- sinks/authentication_type/basicauth/authentication_test.go
- sinks/authentication_type/bearertokenauth/authentication.go
- sinks/authentication_type/bearertokenauth/authentication_test.go
- sinks/service.go
- sinks/sinks_service.go
- ui/src/app/pages/sinks/add/sink-add.component.ts
Enable sinks to be configured with token based authentication.
The required fields for this auth type are:
1. `scheme`
2. `token`
Rather than `scheme` being fixed to `Bearer`, it's customizable because there are [many schemes it could be](https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml).
For example Dynatrace expect the header to be:
`Authorization: Api-Token dt0c01.abc123.abcdefjhij1234567890`
With the following authentication settings configured on a sink:
```json
{
"exporter": {
"endpoint": "https://acme.com/otlphttp/push"
},
"authentication": {
"type": "bearertokenauth",
"scheme": "Api-Token",
"token": "abcdefg"
}
}
```
The resulting yaml configuration is:
```yaml
---
receivers:
kafka:
brokers:
- kafka:9092
topic: otlp_metrics-sink-id-22
protocol_version: …
```
> feat(sinks): enable sinks with token auth.
